// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: worldname.sql

package sqlc

import (
	"context"
)

const selectGuildWorld = `-- name: SelectGuildWorld :one
SELECT id, guild_id, world_name, created_at
FROM guilds_world
WHERE guild_id = $1
LIMIT 1
`

func (q *Queries) SelectGuildWorld(ctx context.Context, guildID string) (GuildsWorld, error) {
	row := q.db.QueryRow(ctx, selectGuildWorld, guildID)
	var i GuildsWorld
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.WorldName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGuildWorld = `-- name: UpsertGuildWorld :exec
INSERT INTO guilds_world (guild_id, world_name, created_at)
VALUES ($1, $2, now())
ON CONFLICT (guild_id)
DO UPDATE SET world_name = EXCLUDED.world_name, created_at = now()
`

type UpsertGuildWorldParams struct {
	GuildID   string
	WorldName string
}

func (q *Queries) UpsertGuildWorld(ctx context.Context, arg UpsertGuildWorldParams) error {
	_, err := q.db.Exec(ctx, upsertGuildWorld, arg.GuildID, arg.WorldName)
	return err
}
