// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: spots.sql

package sqlc

import (
	"context"
)

const selectAllSpots = `-- name: SelectAllSpots :many
SELECT
    id,
    name,
    created_at
FROM
    web_spot
`

func (q *Queries) SelectAllSpots(ctx context.Context) ([]WebSpot, error) {
	rows, err := q.db.Query(ctx, selectAllSpots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebSpot
	for rows.Next() {
		var i WebSpot
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
