// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: channels.sql

package sqlc

import (
	"context"
)

const deleteGuildChannels = `-- name: DeleteGuildChannels :exec
DELETE FROM guild_channels
WHERE guild_id = $1
`

func (q *Queries) DeleteGuildChannels(ctx context.Context, guildID string) error {
	_, err := q.db.Exec(ctx, deleteGuildChannels, guildID)
	return err
}

const insertGuildChannels = `-- name: InsertGuildChannels :exec
INSERT INTO guild_channels (guild_id, channel_id, name, type, parent_id, position)
SELECT $1::text,
       unnest($2::text[]),
       unnest($3::text[]),
       unnest($4::int[]),
       unnest($5::text[]),
       unnest($6::int[])
`

type InsertGuildChannelsParams struct {
	GuildID    string
	ChannelIds []string
	Names      []string
	Types      []int32
	ParentIds  []string
	Positions  []int32
}

func (q *Queries) InsertGuildChannels(ctx context.Context, arg InsertGuildChannelsParams) error {
	_, err := q.db.Exec(ctx, insertGuildChannels,
		arg.GuildID,
		arg.ChannelIds,
		arg.Names,
		arg.Types,
		arg.ParentIds,
		arg.Positions,
	)
	return err
}

const selectGuildChannelsByTypes = `-- name: SelectGuildChannelsByTypes :many
SELECT channel_id, name, type, parent_id, position
FROM guild_channels
WHERE guild_id = $1
  AND type = ANY($2::int[])
ORDER BY position, lower(name), channel_id
`

type SelectGuildChannelsByTypesParams struct {
	GuildID string
	Types   []int32
}

type SelectGuildChannelsByTypesRow struct {
	ChannelID string
	Name      string
	Type      int32
	ParentID  string
	Position  int32
}

func (q *Queries) SelectGuildChannelsByTypes(ctx context.Context, arg SelectGuildChannelsByTypesParams) ([]SelectGuildChannelsByTypesRow, error) {
	rows, err := q.db.Query(ctx, selectGuildChannelsByTypes, arg.GuildID, arg.Types)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectGuildChannelsByTypesRow
	for rows.Next() {
		var i SelectGuildChannelsByTypesRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
