FROM golang:1.21.1

WORKDIR /app

COPY ./ /app

RUN apt-get install git

RUN go install github.com/githubnemo/CompileDaemon@latest

RUN go mod download

ENTRYPOINT CompileDaemon --build='go build -o spot-assistant-bot -buildvcs=false cmd/main.go' --command=./spot-assistant-bot
