version: "2"
sql:
  - engine: "postgresql"
    queries: "query/sessions.sql"
    schema: "../../db/postgresql/schema.sql"
    gen:
      go:
        package: "sqlc"
        sql_package: "pgx/v5"
        out: "sqlc"
