// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: summary_messages.sql

package sqlc

import (
	"context"
)

const deleteSummaryMessage = `-- name: DeleteSummaryMessage :exec
DELETE FROM summary_messages
WHERE id = $1
`

func (q *Queries) DeleteSummaryMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSummaryMessage, id)
	return err
}

const deleteSummaryMessagesForGuild = `-- name: DeleteSummaryMessagesForGuild :exec
DELETE FROM summary_messages
WHERE guild_id = $1 AND channel_id = $2
`

type DeleteSummaryMessagesForGuildParams struct {
	GuildID   string
	ChannelID string
}

func (q *Queries) DeleteSummaryMessagesForGuild(ctx context.Context, arg DeleteSummaryMessagesForGuildParams) error {
	_, err := q.db.Exec(ctx, deleteSummaryMessagesForGuild, arg.GuildID, arg.ChannelID)
	return err
}

const getSummaryMessages = `-- name: GetSummaryMessages :many
SELECT id, guild_id, channel_id, message_id, message_type, message_order, created_at, updated_at FROM summary_messages
WHERE guild_id = $1 AND channel_id = $2
ORDER BY message_order ASC
`

type GetSummaryMessagesParams struct {
	GuildID   string
	ChannelID string
}

func (q *Queries) GetSummaryMessages(ctx context.Context, arg GetSummaryMessagesParams) ([]SummaryMessage, error) {
	rows, err := q.db.Query(ctx, getSummaryMessages, arg.GuildID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryMessage
	for rows.Next() {
		var i SummaryMessage
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageID,
			&i.MessageType,
			&i.MessageOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageTimestamp = `-- name: UpdateMessageTimestamp :exec
UPDATE summary_messages
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateMessageTimestamp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateMessageTimestamp, id)
	return err
}

const upsertSummaryMessage = `-- name: UpsertSummaryMessage :one
INSERT INTO summary_messages (
  guild_id, channel_id, message_id, message_type, message_order, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (guild_id, channel_id, message_type, message_order)
DO UPDATE SET
  message_id = EXCLUDED.message_id,
  updated_at = now()
RETURNING id, guild_id, channel_id, message_id, message_type, message_order, created_at, updated_at
`

type UpsertSummaryMessageParams struct {
	GuildID      string
	ChannelID    string
	MessageID    string
	MessageType  string
	MessageOrder int32
}

func (q *Queries) UpsertSummaryMessage(ctx context.Context, arg UpsertSummaryMessageParams) (SummaryMessage, error) {
	row := q.db.QueryRow(ctx, upsertSummaryMessage,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.MessageType,
		arg.MessageOrder,
	)
	var i SummaryMessage
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageID,
		&i.MessageType,
		&i.MessageOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
