package spots

// DefaultNames is the respawn list ImportDefaults adds, taken from
// internal/infrastructure/db/postgresql/seeds/spots.sql.
var DefaultNames = []string{
	"Rottens (LEFT)",
	"Rottens (RIGHT)",
	"Fire Library",
	"Energy Library",
	"Ice Library",
	"Cobra Bastion",
	"Brachio",
	"Ebb & Flow",
	"Plag Seal",
	"DT Seal",
	"Feru Way",
	"Mirror True Asuras",
	"Bazir",
	"Crater",
	"Thais",
	"Flimsy",
	"Prison -3",
	"Prison -2",
	"Prison -1",
	"Asura Palace",
	"WZ7",
	"WZ8",
	"Roshamuul West",
	"Roshamuul Bones",
	"Rottens (NORTH)",
	"Rottens (SOUTH)",
	"Sparkling Pools (LEFT)",
	"Sparkling Pools (RIGHT)",
	"Monster Graveyard (LEFT)",
	"Monster Graveyard (RIGHT)",
	"Girtablilu",
	"Ingol Surface",
	"Ingol -1",
	"Ingol -2",
	"Ingol -3",
	"Pumin Seal",
	"Jugg Seal",
	"Summer Court",
	"Winter Court",
	"Asura Mirror",
	"Bashmu",
	"Issavi Sphinx -2",
	"Issavi Sewers",
	"Deathlings",
	"Falcon Eagle",
	"Werelions -1",
	"Werelions -2",
	"Werehyenas -1",
	"Werehyenas -2 (NORTH)",
	"Werehyenas -2 (SOUTH)",
	"Buried Cathedral -6",
	"Buried Cathedral -7",
	"Buried Cathedral -8",
	"Burster Spectres",
	"Gazer Spectres",
	"Ripper Spectres",
	"Carnivors -3",
	"Roshamuul Shock Heads",
	"Lower Roshamuul",
	"WZ5",
	"WZ6",
	"WZ9",
	"Oramond Demons",
	"Exotic Cave -1",
	"Exotic Cave -2",
	"Lava Lurkers",
	"Otherworld",
	"DT Inq",
	"Nightmare Isle",
	"Pirat Mine",
	"Glooth Bandits (EAST)",
	"Glooth Bandits (WEST)",
	"Lower Spike -6",
	"Catacombs (RIGHT)",
	"Catacombs (LEFT + MID)",
	"Turtle Marapur -1",
	"Turtle Marapur -2",
	"Deeper Banuta -7",
	"Minotaur Cults -1",
	"Minotaur Cults -2",
	"Orc Cults",
	"Carlin Cults",
	"Barkless",
	"Issavi Sphinx -1",
	"Issavi Sphinx Surface",
	"Flimsy Port Hope",
	"Medusa Tower",
	"Glooth Tower",
	"Draken Walls (NORTH)",
	"Draken Walls (SOUTH)",
	"Lizard City",
	"Oramond West",
	"Grim Reapers Drefia",
	"Pirate Ship -1",
	"Pirate Ship -2",
	"Nagas -1",
	"Nagas -2",
	"Cobra Bastion -1",
	"Mini Roshamuul",
	"Lower Spike -7",
	"Darashia Skeletons",
	"Lower Spike -8",
	"Wyrm Lair Drefia -1",
	"Wyrm Lair Drefia -2",
	"Glooth Bandits (SOUTH)",
	"Sea Serpents (NORTH)",
	"Sea Serpents (SOUTH)",
	"Yalahar Demons (EAST)",
	"Yalahar Demons (WEST)",
	"War Golems (EAST)",
	"War Golems (WEST)",
	"Grim Reapers Yalahar",
	"Hellspawns Yalahar",
	"Falcon Castle",
	"WOTE 8",
	"WOTE 10",
	"Yielothax Cave",
	"Razachai Ghastly Dragon Lair",
	"Zao Palace Ghastly Dragons",
	"Hive Tower (EAST)",
	"Hive Tower (WEST)",
	"Hive Overseers",
	"Deepling Tyrants",
	"Issavi Ogres Cave",
	"Krailos Nightmares",
	"Carnivors -2",
	"Deeper Banuta -8",
	"Issavi (WEST)",
	"Floating Savants (MOTA) -1",
	"Floating Savants (MOTA) -2",
	"Fury Oramond",
	"Oramond Minos South",
	"Oramond Minos Camp",
	"Hydras Oramond",
	"Oramond Raid (Minotaurs)",
	"Oramond Raid (Mechanical Creatures)",
	"Oramond Raid (Wild Life)",
	"War Golems Hero of Rathleton",
	"Roshamuul Dark Grounds",
	"Darashia Dragon Lair",
	"Putrid Mummy -1",
	"Putrid Mummy -2",
	"Hero Cave -2",
	"Hero Cave -3",
	"Weremobs Edron",
	"Weremobs Cormaya",
	"Edron Vampire Crypt",
	"Crypt Warriors",
	"Carnisylvans",
	"Iks -1",
	"Iks -2",
	"Iks -3",
	"Giant Spiders Port Hope",
	"Wyrm Cave Liberty Bay",
	"Goroma Demons",
	"Dragon Lords Fenrock",
	"Dragon Lords POI",
	"Seacrest Serpents (NORTH)",
	"Infernatil Seal (POI)",
	"Infernatil Seal (Feru)",
	"Goroma Medusa Cave",
	"Issavi Puzzle",
	"Crystal Enigma (NORTH)",
	"Crystal Enigma (SOUTH)",
	"Shapers (Holy Portal)",
	"Mother of Scarabs Lair",
	"Stonerefiners",
	"Weretigers -1",
	"Weretigers -2",
	"Werecrocodiles -1",
	"Werecrocodiles -2",
	"Diremaw Task Area",
	"Hero Cave -1 (Bonebeasts)",
	"Souleater Mountains",
	"Krailos Spider Lair",
	"Fire Dragon Dojo",
	"Edron Demons (Annihilator)",
	"WZ4",
	"Seacrest Serpents (WEST)",
	"Zao Mutated Bats/Tigers",
	"Crystal Cave Inq",
	"Carnivors -1",
	"Grimvale -1",
	"Grimvale -2",
	"Grimvale -3",
	"Grimvale -4",
	"Cults Yalahar",
	"Verminor Seal (POI)",
	"Nimmersatt's Breeding Ground -7 (entrance)",
	"Nimmersatt's Breeding Ground -6",
	"Bulltaur Lair -1",
	"Bulltaur Lair -2",
	"Kha'zeel Hydras Big Spawn",
	"Undead Seal",
	"Hydras Forbidden Lands",
	"Banuta (Apes) -1",
	"Banuta (Apes) -2",
	"Deeper Banuta -3",
	"Deeper Banuta -4",
	"Deeper Banuta -5",
	"Deeper Banuta -6",
	"Temple of Equilibrium",
	"DT PoI",
	"Vats Inq",
	"Magicians Yalahar",
	"Okolnir Frost Dragons",
	"Issavi (EAST)",
	"Upper Roshamuul (Depot)",
}
