// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/webuser"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Complete(ctx context.Context, code string) (*webuser.User, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 *webuser.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*webuser.User, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *webuser.User); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webuser.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockAuthService_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockAuthService_Expecter) Complete(ctx any, code any) *MockAuthService_Complete_Call {
	return &MockAuthService_Complete_Call{Call: _e.mock.On("Complete", ctx, code)}
}

func (_c *MockAuthService_Complete_Call) Run(run func(ctx context.Context, code string)) *MockAuthService_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Complete_Call) Return(user *webuser.User, err error) *MockAuthService_Complete_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_Complete_Call) RunAndReturn(run func(ctx context.Context, code string) (*webuser.User, error)) *MockAuthService_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// LoginURL provides a mock function for the type MockAuthService
func (_mock *MockAuthService) LoginURL(state string) string {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for LoginURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuthService_LoginURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginURL'
type MockAuthService_LoginURL_Call struct {
	*mock.Call
}

// LoginURL is a helper method to define mock.On call
//   - state string
func (_e *MockAuthService_Expecter) LoginURL(state any) *MockAuthService_LoginURL_Call {
	return &MockAuthService_LoginURL_Call{Call: _e.mock.On("LoginURL", state)}
}

func (_c *MockAuthService_LoginURL_Call) Run(run func(state string)) *MockAuthService_LoginURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_LoginURL_Call) Return(s string) *MockAuthService_LoginURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuthService_LoginURL_Call) RunAndReturn(run func(state string) string) *MockAuthService_LoginURL_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type MockAuthService
func (_mock *MockAuthService) User(ctx context.Context, userID string) (*webuser.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 *webuser.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*webuser.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *webuser.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webuser.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockAuthService_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthService_Expecter) User(ctx any, userID any) *MockAuthService_User_Call {
	return &MockAuthService_User_Call{Call: _e.mock.On("User", ctx, userID)}
}

func (_c *MockAuthService_User_Call) Run(run func(ctx context.Context, userID string)) *MockAuthService_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_User_Call) Return(user *webuser.User, err error) *MockAuthService_User_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_User_Call) RunAndReturn(run func(ctx context.Context, userID string) (*webuser.User, error)) *MockAuthService_User_Call {
	_c.Call.Return(run)
	return _c
}
