// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"spot-assistant/internal/core/dto/book"
	"spot-assistant/internal/core/dto/guild"
	"spot-assistant/internal/core/dto/member"
	"spot-assistant/internal/core/dto/reservation"
	"spot-assistant/internal/core/dto/summary"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommunicationService creates a new instance of MockCommunicationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommunicationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommunicationService {
	mock := &MockCommunicationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommunicationService is an autogenerated mock type for the CommunicationService type
type MockCommunicationService struct {
	mock.Mock
}

type MockCommunicationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommunicationService) EXPECT() *MockCommunicationService_Expecter {
	return &MockCommunicationService_Expecter{mock: &_m.Mock}
}

// NotifyOverbookedMember provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) NotifyOverbookedMember(request book.BookRequest, res *reservation.ClippedOrRemovedReservation) {
	_mock.Called(request, res)
	return
}

// MockCommunicationService_NotifyOverbookedMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyOverbookedMember'
type MockCommunicationService_NotifyOverbookedMember_Call struct {
	*mock.Call
}

// NotifyOverbookedMember is a helper method to define mock.On call
//   - request book.BookRequest
//   - res *reservation.ClippedOrRemovedReservation
func (_e *MockCommunicationService_Expecter) NotifyOverbookedMember(request interface{}, res interface{}) *MockCommunicationService_NotifyOverbookedMember_Call {
	return &MockCommunicationService_NotifyOverbookedMember_Call{Call: _e.mock.On("NotifyOverbookedMember", request, res)}
}

func (_c *MockCommunicationService_NotifyOverbookedMember_Call) Run(run func(request book.BookRequest, res *reservation.ClippedOrRemovedReservation)) *MockCommunicationService_NotifyOverbookedMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 book.BookRequest
		if args[0] != nil {
			arg0 = args[0].(book.BookRequest)
		}
		var arg1 *reservation.ClippedOrRemovedReservation
		if args[1] != nil {
			arg1 = args[1].(*reservation.ClippedOrRemovedReservation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommunicationService_NotifyOverbookedMember_Call) Return() *MockCommunicationService_NotifyOverbookedMember_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommunicationService_NotifyOverbookedMember_Call) RunAndReturn(run func(request book.BookRequest, res *reservation.ClippedOrRemovedReservation)) *MockCommunicationService_NotifyOverbookedMember_Call {
	_c.Run(run)
	return _c
}

// NotifyUpcomingReservation provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) NotifyUpcomingReservation(guild1 *guild.Guild, member1 *member.Member, spotName string, startAt time.Time) error {
	ret := _mock.Called(guild1, member1, spotName, startAt)

	if len(ret) == 0 {
		panic("no return value specified for NotifyUpcomingReservation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*guild.Guild, *member.Member, string, time.Time) error); ok {
		r0 = returnFunc(guild1, member1, spotName, startAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommunicationService_NotifyUpcomingReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyUpcomingReservation'
type MockCommunicationService_NotifyUpcomingReservation_Call struct {
	*mock.Call
}

// NotifyUpcomingReservation is a helper method to define mock.On call
//   - guild1 *guild.Guild
//   - member1 *member.Member
//   - spotName string
//   - startAt time.Time
func (_e *MockCommunicationService_Expecter) NotifyUpcomingReservation(guild1 interface{}, member1 interface{}, spotName interface{}, startAt interface{}) *MockCommunicationService_NotifyUpcomingReservation_Call {
	return &MockCommunicationService_NotifyUpcomingReservation_Call{Call: _e.mock.On("NotifyUpcomingReservation", guild1, member1, spotName, startAt)}
}

func (_c *MockCommunicationService_NotifyUpcomingReservation_Call) Run(run func(guild1 *guild.Guild, member1 *member.Member, spotName string, startAt time.Time)) *MockCommunicationService_NotifyUpcomingReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *guild.Guild
		if args[0] != nil {
			arg0 = args[0].(*guild.Guild)
		}
		var arg1 *member.Member
		if args[1] != nil {
			arg1 = args[1].(*member.Member)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCommunicationService_NotifyUpcomingReservation_Call) Return(err error) *MockCommunicationService_NotifyUpcomingReservation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommunicationService_NotifyUpcomingReservation_Call) RunAndReturn(run func(guild1 *guild.Guild, member1 *member.Member, spotName string, startAt time.Time) error) *MockCommunicationService_NotifyUpcomingReservation_Call {
	_c.Call.Return(run)
	return _c
}

// SendGuildSummary provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) SendGuildSummary(guild1 *guild.Guild, summary1 *summary.Summary) error {
	ret := _mock.Called(guild1, summary1)

	if len(ret) == 0 {
		panic("no return value specified for SendGuildSummary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*guild.Guild, *summary.Summary) error); ok {
		r0 = returnFunc(guild1, summary1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommunicationService_SendGuildSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendGuildSummary'
type MockCommunicationService_SendGuildSummary_Call struct {
	*mock.Call
}

// SendGuildSummary is a helper method to define mock.On call
//   - guild1 *guild.Guild
//   - summary1 *summary.Summary
func (_e *MockCommunicationService_Expecter) SendGuildSummary(guild1 interface{}, summary1 interface{}) *MockCommunicationService_SendGuildSummary_Call {
	return &MockCommunicationService_SendGuildSummary_Call{Call: _e.mock.On("SendGuildSummary", guild1, summary1)}
}

func (_c *MockCommunicationService_SendGuildSummary_Call) Run(run func(guild1 *guild.Guild, summary1 *summary.Summary)) *MockCommunicationService_SendGuildSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *guild.Guild
		if args[0] != nil {
			arg0 = args[0].(*guild.Guild)
		}
		var arg1 *summary.Summary
		if args[1] != nil {
			arg1 = args[1].(*summary.Summary)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommunicationService_SendGuildSummary_Call) Return(err error) *MockCommunicationService_SendGuildSummary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommunicationService_SendGuildSummary_Call) RunAndReturn(run func(guild1 *guild.Guild, summary1 *summary.Summary) error) *MockCommunicationService_SendGuildSummary_Call {
	_c.Call.Return(run)
	return _c
}

// SendPrivateSummary provides a mock function for the type MockCommunicationService
func (_mock *MockCommunicationService) SendPrivateSummary(request summary.PrivateSummaryRequest, summary1 *summary.Summary) error {
	ret := _mock.Called(request, summary1)

	if len(ret) == 0 {
		panic("no return value specified for SendPrivateSummary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(summary.PrivateSummaryRequest, *summary.Summary) error); ok {
		r0 = returnFunc(request, summary1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommunicationService_SendPrivateSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPrivateSummary'
type MockCommunicationService_SendPrivateSummary_Call struct {
	*mock.Call
}

// SendPrivateSummary is a helper method to define mock.On call
//   - request summary.PrivateSummaryRequest
//   - summary1 *summary.Summary
func (_e *MockCommunicationService_Expecter) SendPrivateSummary(request interface{}, summary1 interface{}) *MockCommunicationService_SendPrivateSummary_Call {
	return &MockCommunicationService_SendPrivateSummary_Call{Call: _e.mock.On("SendPrivateSummary", request, summary1)}
}

func (_c *MockCommunicationService_SendPrivateSummary_Call) Run(run func(request summary.PrivateSummaryRequest, summary1 *summary.Summary)) *MockCommunicationService_SendPrivateSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 summary.PrivateSummaryRequest
		if args[0] != nil {
			arg0 = args[0].(summary.PrivateSummaryRequest)
		}
		var arg1 *summary.Summary
		if args[1] != nil {
			arg1 = args[1].(*summary.Summary)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommunicationService_SendPrivateSummary_Call) Return(err error) *MockCommunicationService_SendPrivateSummary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommunicationService_SendPrivateSummary_Call) RunAndReturn(run func(request summary.PrivateSummaryRequest, summary1 *summary.Summary) error) *MockCommunicationService_SendPrivateSummary_Call {
	_c.Call.Return(run)
	return _c
}
