// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/experience"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExperienceRepository creates a new instance of MockExperienceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExperienceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExperienceRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockExperienceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockExperienceRepository is an autogenerated mock type for the ExperienceRepository type
type MockExperienceRepository struct {
	mock.Mock
}

type MockExperienceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExperienceRepository) EXPECT() *MockExperienceRepository_Expecter {
	return &MockExperienceRepository_Expecter{mock: &_m.Mock}
}

// FirstRunObservedAt provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) FirstRunObservedAt(ctx context.Context, worldName string) (time.Time, error) {
	ret := _mock.Called(ctx, worldName)

	if len(ret) == 0 {
		panic("no return value specified for FirstRunObservedAt")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return returnFunc(ctx, worldName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = returnFunc(ctx, worldName)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, worldName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_FirstRunObservedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstRunObservedAt'
type MockExperienceRepository_FirstRunObservedAt_Call struct {
	*mock.Call
}

// FirstRunObservedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - worldName string
func (_e *MockExperienceRepository_Expecter) FirstRunObservedAt(ctx any, worldName any) *MockExperienceRepository_FirstRunObservedAt_Call {
	return &MockExperienceRepository_FirstRunObservedAt_Call{Call: _e.mock.On("FirstRunObservedAt", ctx, worldName)}
}

func (_c *MockExperienceRepository_FirstRunObservedAt_Call) Run(run func(ctx context.Context, worldName string)) *MockExperienceRepository_FirstRunObservedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_FirstRunObservedAt_Call) Return(time1 time.Time, err error) *MockExperienceRepository_FirstRunObservedAt_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockExperienceRepository_FirstRunObservedAt_Call) RunAndReturn(run func(ctx context.Context, worldName string) (time.Time, error)) *MockExperienceRepository_FirstRunObservedAt_Call {
	_c.Call.Return(run)
	return _c
}

// FirstRunObservedAtOrAfter provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) FirstRunObservedAtOrAfter(ctx context.Context, worldName string, t time.Time) (time.Time, error) {
	ret := _mock.Called(ctx, worldName, t)

	if len(ret) == 0 {
		panic("no return value specified for FirstRunObservedAtOrAfter")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (time.Time, error)); ok {
		return returnFunc(ctx, worldName, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) time.Time); ok {
		r0 = returnFunc(ctx, worldName, t)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, worldName, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_FirstRunObservedAtOrAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstRunObservedAtOrAfter'
type MockExperienceRepository_FirstRunObservedAtOrAfter_Call struct {
	*mock.Call
}

// FirstRunObservedAtOrAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - worldName string
//   - t time.Time
func (_e *MockExperienceRepository_Expecter) FirstRunObservedAtOrAfter(ctx any, worldName any, t any) *MockExperienceRepository_FirstRunObservedAtOrAfter_Call {
	return &MockExperienceRepository_FirstRunObservedAtOrAfter_Call{Call: _e.mock.On("FirstRunObservedAtOrAfter", ctx, worldName, t)}
}

func (_c *MockExperienceRepository_FirstRunObservedAtOrAfter_Call) Run(run func(ctx context.Context, worldName string, t time.Time)) *MockExperienceRepository_FirstRunObservedAtOrAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_FirstRunObservedAtOrAfter_Call) Return(time1 time.Time, err error) *MockExperienceRepository_FirstRunObservedAtOrAfter_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockExperienceRepository_FirstRunObservedAtOrAfter_Call) RunAndReturn(run func(ctx context.Context, worldName string, t time.Time) (time.Time, error)) *MockExperienceRepository_FirstRunObservedAtOrAfter_Call {
	_c.Call.Return(run)
	return _c
}

// FirstSnapshotAfter provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) FirstSnapshotAfter(ctx context.Context, worldName string, key string, from time.Time, to time.Time) (*experience.Snapshot, error) {
	ret := _mock.Called(ctx, worldName, key, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FirstSnapshotAfter")
	}

	var r0 *experience.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) (*experience.Snapshot, error)); ok {
		return returnFunc(ctx, worldName, key, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) *experience.Snapshot); ok {
		r0 = returnFunc(ctx, worldName, key, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*experience.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, worldName, key, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_FirstSnapshotAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstSnapshotAfter'
type MockExperienceRepository_FirstSnapshotAfter_Call struct {
	*mock.Call
}

// FirstSnapshotAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - worldName string
//   - key string
//   - from time.Time
//   - to time.Time
func (_e *MockExperienceRepository_Expecter) FirstSnapshotAfter(ctx any, worldName any, key any, from any, to any) *MockExperienceRepository_FirstSnapshotAfter_Call {
	return &MockExperienceRepository_FirstSnapshotAfter_Call{Call: _e.mock.On("FirstSnapshotAfter", ctx, worldName, key, from, to)}
}

func (_c *MockExperienceRepository_FirstSnapshotAfter_Call) Run(run func(ctx context.Context, worldName string, key string, from time.Time, to time.Time)) *MockExperienceRepository_FirstSnapshotAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_FirstSnapshotAfter_Call) Return(snapshot *experience.Snapshot, err error) *MockExperienceRepository_FirstSnapshotAfter_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockExperienceRepository_FirstSnapshotAfter_Call) RunAndReturn(run func(ctx context.Context, worldName string, key string, from time.Time, to time.Time) (*experience.Snapshot, error)) *MockExperienceRepository_FirstSnapshotAfter_Call {
	_c.Call.Return(run)
	return _c
}

// InsertReservationExperience provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) InsertReservationExperience(ctx context.Context, rows []experience.ReservationExperience) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for InsertReservationExperience")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []experience.ReservationExperience) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExperienceRepository_InsertReservationExperience_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertReservationExperience'
type MockExperienceRepository_InsertReservationExperience_Call struct {
	*mock.Call
}

// InsertReservationExperience is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []experience.ReservationExperience
func (_e *MockExperienceRepository_Expecter) InsertReservationExperience(ctx any, rows any) *MockExperienceRepository_InsertReservationExperience_Call {
	return &MockExperienceRepository_InsertReservationExperience_Call{Call: _e.mock.On("InsertReservationExperience", ctx, rows)}
}

func (_c *MockExperienceRepository_InsertReservationExperience_Call) Run(run func(ctx context.Context, rows []experience.ReservationExperience)) *MockExperienceRepository_InsertReservationExperience_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []experience.ReservationExperience
		if args[1] != nil {
			arg1 = args[1].([]experience.ReservationExperience)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_InsertReservationExperience_Call) Return(err error) *MockExperienceRepository_InsertReservationExperience_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExperienceRepository_InsertReservationExperience_Call) RunAndReturn(run func(ctx context.Context, rows []experience.ReservationExperience) error) *MockExperienceRepository_InsertReservationExperience_Call {
	_c.Call.Return(run)
	return _c
}

// LatestSnapshots provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) LatestSnapshots(ctx context.Context, worldName string, keys []string) (map[string]experience.Snapshot, error) {
	ret := _mock.Called(ctx, worldName, keys)

	if len(ret) == 0 {
		panic("no return value specified for LatestSnapshots")
	}

	var r0 map[string]experience.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (map[string]experience.Snapshot, error)); ok {
		return returnFunc(ctx, worldName, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) map[string]experience.Snapshot); ok {
		r0 = returnFunc(ctx, worldName, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]experience.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, worldName, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_LatestSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestSnapshots'
type MockExperienceRepository_LatestSnapshots_Call struct {
	*mock.Call
}

// LatestSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - worldName string
//   - keys []string
func (_e *MockExperienceRepository_Expecter) LatestSnapshots(ctx any, worldName any, keys any) *MockExperienceRepository_LatestSnapshots_Call {
	return &MockExperienceRepository_LatestSnapshots_Call{Call: _e.mock.On("LatestSnapshots", ctx, worldName, keys)}
}

func (_c *MockExperienceRepository_LatestSnapshots_Call) Run(run func(ctx context.Context, worldName string, keys []string)) *MockExperienceRepository_LatestSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_LatestSnapshots_Call) Return(stringToSnapshot map[string]experience.Snapshot, err error) *MockExperienceRepository_LatestSnapshots_Call {
	_c.Call.Return(stringToSnapshot, err)
	return _c
}

func (_c *MockExperienceRepository_LatestSnapshots_Call) RunAndReturn(run func(ctx context.Context, worldName string, keys []string) (map[string]experience.Snapshot, error)) *MockExperienceRepository_LatestSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrackedCharacterKeys provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) ListTrackedCharacterKeys(ctx context.Context, worldName string, since time.Time) ([]string, error) {
	ret := _mock.Called(ctx, worldName, since)

	if len(ret) == 0 {
		panic("no return value specified for ListTrackedCharacterKeys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]string, error)); ok {
		return returnFunc(ctx, worldName, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) []string); ok {
		r0 = returnFunc(ctx, worldName, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, worldName, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_ListTrackedCharacterKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrackedCharacterKeys'
type MockExperienceRepository_ListTrackedCharacterKeys_Call struct {
	*mock.Call
}

// ListTrackedCharacterKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - worldName string
//   - since time.Time
func (_e *MockExperienceRepository_Expecter) ListTrackedCharacterKeys(ctx any, worldName any, since any) *MockExperienceRepository_ListTrackedCharacterKeys_Call {
	return &MockExperienceRepository_ListTrackedCharacterKeys_Call{Call: _e.mock.On("ListTrackedCharacterKeys", ctx, worldName, since)}
}

func (_c *MockExperienceRepository_ListTrackedCharacterKeys_Call) Run(run func(ctx context.Context, worldName string, since time.Time)) *MockExperienceRepository_ListTrackedCharacterKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_ListTrackedCharacterKeys_Call) Return(strings []string, err error) *MockExperienceRepository_ListTrackedCharacterKeys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockExperienceRepository_ListTrackedCharacterKeys_Call) RunAndReturn(run func(ctx context.Context, worldName string, since time.Time) ([]string, error)) *MockExperienceRepository_ListTrackedCharacterKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrackedWorlds provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) ListTrackedWorlds(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTrackedWorlds")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_ListTrackedWorlds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrackedWorlds'
type MockExperienceRepository_ListTrackedWorlds_Call struct {
	*mock.Call
}

// ListTrackedWorlds is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExperienceRepository_Expecter) ListTrackedWorlds(ctx any) *MockExperienceRepository_ListTrackedWorlds_Call {
	return &MockExperienceRepository_ListTrackedWorlds_Call{Call: _e.mock.On("ListTrackedWorlds", ctx)}
}

func (_c *MockExperienceRepository_ListTrackedWorlds_Call) Run(run func(ctx context.Context)) *MockExperienceRepository_ListTrackedWorlds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_ListTrackedWorlds_Call) Return(strings []string, err error) *MockExperienceRepository_ListTrackedWorlds_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockExperienceRepository_ListTrackedWorlds_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockExperienceRepository_ListTrackedWorlds_Call {
	_c.Call.Return(run)
	return _c
}

// PendingReservations provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) PendingReservations(ctx context.Context, worldName string, startFrom time.Time, endFrom time.Time, endTo time.Time) ([]experience.PendingReservation, error) {
	ret := _mock.Called(ctx, worldName, startFrom, endFrom, endTo)

	if len(ret) == 0 {
		panic("no return value specified for PendingReservations")
	}

	var r0 []experience.PendingReservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, time.Time) ([]experience.PendingReservation, error)); ok {
		return returnFunc(ctx, worldName, startFrom, endFrom, endTo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, time.Time) []experience.PendingReservation); ok {
		r0 = returnFunc(ctx, worldName, startFrom, endFrom, endTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]experience.PendingReservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, worldName, startFrom, endFrom, endTo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_PendingReservations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingReservations'
type MockExperienceRepository_PendingReservations_Call struct {
	*mock.Call
}

// PendingReservations is a helper method to define mock.On call
//   - ctx context.Context
//   - worldName string
//   - startFrom time.Time
//   - endFrom time.Time
//   - endTo time.Time
func (_e *MockExperienceRepository_Expecter) PendingReservations(ctx any, worldName any, startFrom any, endFrom any, endTo any) *MockExperienceRepository_PendingReservations_Call {
	return &MockExperienceRepository_PendingReservations_Call{Call: _e.mock.On("PendingReservations", ctx, worldName, startFrom, endFrom, endTo)}
}

func (_c *MockExperienceRepository_PendingReservations_Call) Run(run func(ctx context.Context, worldName string, startFrom time.Time, endFrom time.Time, endTo time.Time)) *MockExperienceRepository_PendingReservations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_PendingReservations_Call) Return(pendingReservations []experience.PendingReservation, err error) *MockExperienceRepository_PendingReservations_Call {
	_c.Call.Return(pendingReservations, err)
	return _c
}

func (_c *MockExperienceRepository_PendingReservations_Call) RunAndReturn(run func(ctx context.Context, worldName string, startFrom time.Time, endFrom time.Time, endTo time.Time) ([]experience.PendingReservation, error)) *MockExperienceRepository_PendingReservations_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRun provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) SaveRun(ctx context.Context, result experience.RunResult) error {
	ret := _mock.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for SaveRun")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, experience.RunResult) error); ok {
		r0 = returnFunc(ctx, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExperienceRepository_SaveRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRun'
type MockExperienceRepository_SaveRun_Call struct {
	*mock.Call
}

// SaveRun is a helper method to define mock.On call
//   - ctx context.Context
//   - result experience.RunResult
func (_e *MockExperienceRepository_Expecter) SaveRun(ctx any, result any) *MockExperienceRepository_SaveRun_Call {
	return &MockExperienceRepository_SaveRun_Call{Call: _e.mock.On("SaveRun", ctx, result)}
}

func (_c *MockExperienceRepository_SaveRun_Call) Run(run func(ctx context.Context, result experience.RunResult)) *MockExperienceRepository_SaveRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 experience.RunResult
		if args[1] != nil {
			arg1 = args[1].(experience.RunResult)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_SaveRun_Call) Return(err error) *MockExperienceRepository_SaveRun_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExperienceRepository_SaveRun_Call) RunAndReturn(run func(ctx context.Context, result experience.RunResult) error) *MockExperienceRepository_SaveRun_Call {
	_c.Call.Return(run)
	return _c
}

// SnapshotAtOrBefore provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) SnapshotAtOrBefore(ctx context.Context, worldName string, key string, t time.Time) (*experience.Snapshot, error) {
	ret := _mock.Called(ctx, worldName, key, t)

	if len(ret) == 0 {
		panic("no return value specified for SnapshotAtOrBefore")
	}

	var r0 *experience.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*experience.Snapshot, error)); ok {
		return returnFunc(ctx, worldName, key, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *experience.Snapshot); ok {
		r0 = returnFunc(ctx, worldName, key, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*experience.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, worldName, key, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_SnapshotAtOrBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnapshotAtOrBefore'
type MockExperienceRepository_SnapshotAtOrBefore_Call struct {
	*mock.Call
}

// SnapshotAtOrBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - worldName string
//   - key string
//   - t time.Time
func (_e *MockExperienceRepository_Expecter) SnapshotAtOrBefore(ctx any, worldName any, key any, t any) *MockExperienceRepository_SnapshotAtOrBefore_Call {
	return &MockExperienceRepository_SnapshotAtOrBefore_Call{Call: _e.mock.On("SnapshotAtOrBefore", ctx, worldName, key, t)}
}

func (_c *MockExperienceRepository_SnapshotAtOrBefore_Call) Run(run func(ctx context.Context, worldName string, key string, t time.Time)) *MockExperienceRepository_SnapshotAtOrBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_SnapshotAtOrBefore_Call) Return(snapshot *experience.Snapshot, err error) *MockExperienceRepository_SnapshotAtOrBefore_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockExperienceRepository_SnapshotAtOrBefore_Call) RunAndReturn(run func(ctx context.Context, worldName string, key string, t time.Time) (*experience.Snapshot, error)) *MockExperienceRepository_SnapshotAtOrBefore_Call {
	_c.Call.Return(run)
	return _c
}

// SnapshotHistory provides a mock function for the type MockExperienceRepository
func (_mock *MockExperienceRepository) SnapshotHistory(ctx context.Context, worldName string, key string, from time.Time, to time.Time) ([]experience.Snapshot, error) {
	ret := _mock.Called(ctx, worldName, key, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SnapshotHistory")
	}

	var r0 []experience.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) ([]experience.Snapshot, error)); ok {
		return returnFunc(ctx, worldName, key, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) []experience.Snapshot); ok {
		r0 = returnFunc(ctx, worldName, key, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]experience.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, worldName, key, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExperienceRepository_SnapshotHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnapshotHistory'
type MockExperienceRepository_SnapshotHistory_Call struct {
	*mock.Call
}

// SnapshotHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - worldName string
//   - key string
//   - from time.Time
//   - to time.Time
func (_e *MockExperienceRepository_Expecter) SnapshotHistory(ctx any, worldName any, key any, from any, to any) *MockExperienceRepository_SnapshotHistory_Call {
	return &MockExperienceRepository_SnapshotHistory_Call{Call: _e.mock.On("SnapshotHistory", ctx, worldName, key, from, to)}
}

func (_c *MockExperienceRepository_SnapshotHistory_Call) Run(run func(ctx context.Context, worldName string, key string, from time.Time, to time.Time)) *MockExperienceRepository_SnapshotHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockExperienceRepository_SnapshotHistory_Call) Return(snapshots []experience.Snapshot, err error) *MockExperienceRepository_SnapshotHistory_Call {
	_c.Call.Return(snapshots, err)
	return _c
}

func (_c *MockExperienceRepository_SnapshotHistory_Call) RunAndReturn(run func(ctx context.Context, worldName string, key string, from time.Time, to time.Time) ([]experience.Snapshot, error)) *MockExperienceRepository_SnapshotHistory_Call {
	_c.Call.Return(run)
	return _c
}
