// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/discord"
	"spot-assistant/internal/core/dto/guildconfig"
	"spot-assistant/internal/core/dto/role"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGuildSettingsService creates a new instance of MockGuildSettingsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuildSettingsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuildSettingsService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGuildSettingsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGuildSettingsService is an autogenerated mock type for the GuildSettingsService type
type MockGuildSettingsService struct {
	mock.Mock
}

type MockGuildSettingsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuildSettingsService) EXPECT() *MockGuildSettingsService_Expecter {
	return &MockGuildSettingsService_Expecter{mock: &_m.Mock}
}

// Channels provides a mock function for the type MockGuildSettingsService
func (_mock *MockGuildSettingsService) Channels(ctx context.Context, guildID string) ([]*discord.Channel, error) {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for Channels")
	}

	var r0 []*discord.Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*discord.Channel, error)); ok {
		return returnFunc(ctx, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*discord.Channel); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*discord.Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuildSettingsService_Channels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channels'
type MockGuildSettingsService_Channels_Call struct {
	*mock.Call
}

// Channels is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockGuildSettingsService_Expecter) Channels(ctx any, guildID any) *MockGuildSettingsService_Channels_Call {
	return &MockGuildSettingsService_Channels_Call{Call: _e.mock.On("Channels", ctx, guildID)}
}

func (_c *MockGuildSettingsService_Channels_Call) Run(run func(ctx context.Context, guildID string)) *MockGuildSettingsService_Channels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuildSettingsService_Channels_Call) Return(channels []*discord.Channel, err error) *MockGuildSettingsService_Channels_Call {
	_c.Call.Return(channels, err)
	return _c
}

func (_c *MockGuildSettingsService_Channels_Call) RunAndReturn(run func(ctx context.Context, guildID string) ([]*discord.Channel, error)) *MockGuildSettingsService_Channels_Call {
	_c.Call.Return(run)
	return _c
}

// RequestResync provides a mock function for the type MockGuildSettingsService
func (_mock *MockGuildSettingsService) RequestResync(ctx context.Context, guildID string) (time.Duration, error) {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for RequestResync")
	}

	var r0 time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return returnFunc(ctx, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuildSettingsService_RequestResync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestResync'
type MockGuildSettingsService_RequestResync_Call struct {
	*mock.Call
}

// RequestResync is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockGuildSettingsService_Expecter) RequestResync(ctx any, guildID any) *MockGuildSettingsService_RequestResync_Call {
	return &MockGuildSettingsService_RequestResync_Call{Call: _e.mock.On("RequestResync", ctx, guildID)}
}

func (_c *MockGuildSettingsService_RequestResync_Call) Run(run func(ctx context.Context, guildID string)) *MockGuildSettingsService_RequestResync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuildSettingsService_RequestResync_Call) Return(retryAfter time.Duration, err error) *MockGuildSettingsService_RequestResync_Call {
	_c.Call.Return(retryAfter, err)
	return _c
}

func (_c *MockGuildSettingsService_RequestResync_Call) RunAndReturn(run func(ctx context.Context, guildID string) (time.Duration, error)) *MockGuildSettingsService_RequestResync_Call {
	_c.Call.Return(run)
	return _c
}

// Roles provides a mock function for the type MockGuildSettingsService
func (_mock *MockGuildSettingsService) Roles(ctx context.Context, guildID string) ([]*role.Role, error) {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for Roles")
	}

	var r0 []*role.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*role.Role, error)); ok {
		return returnFunc(ctx, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*role.Role); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*role.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuildSettingsService_Roles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Roles'
type MockGuildSettingsService_Roles_Call struct {
	*mock.Call
}

// Roles is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockGuildSettingsService_Expecter) Roles(ctx any, guildID any) *MockGuildSettingsService_Roles_Call {
	return &MockGuildSettingsService_Roles_Call{Call: _e.mock.On("Roles", ctx, guildID)}
}

func (_c *MockGuildSettingsService_Roles_Call) Run(run func(ctx context.Context, guildID string)) *MockGuildSettingsService_Roles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuildSettingsService_Roles_Call) Return(roles []*role.Role, err error) *MockGuildSettingsService_Roles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockGuildSettingsService_Roles_Call) RunAndReturn(run func(ctx context.Context, guildID string) ([]*role.Role, error)) *MockGuildSettingsService_Roles_Call {
	_c.Call.Return(run)
	return _c
}

// SetChannels provides a mock function for the type MockGuildSettingsService
func (_mock *MockGuildSettingsService) SetChannels(ctx context.Context, guildID string, commandChannelID string, summaryChannelID string) error {
	ret := _mock.Called(ctx, guildID, commandChannelID, summaryChannelID)

	if len(ret) == 0 {
		panic("no return value specified for SetChannels")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, guildID, commandChannelID, summaryChannelID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGuildSettingsService_SetChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChannels'
type MockGuildSettingsService_SetChannels_Call struct {
	*mock.Call
}

// SetChannels is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - commandChannelID string
//   - summaryChannelID string
func (_e *MockGuildSettingsService_Expecter) SetChannels(ctx any, guildID any, commandChannelID any, summaryChannelID any) *MockGuildSettingsService_SetChannels_Call {
	return &MockGuildSettingsService_SetChannels_Call{Call: _e.mock.On("SetChannels", ctx, guildID, commandChannelID, summaryChannelID)}
}

func (_c *MockGuildSettingsService_SetChannels_Call) Run(run func(ctx context.Context, guildID string, commandChannelID string, summaryChannelID string)) *MockGuildSettingsService_SetChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGuildSettingsService_SetChannels_Call) Return(err error) *MockGuildSettingsService_SetChannels_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGuildSettingsService_SetChannels_Call) RunAndReturn(run func(ctx context.Context, guildID string, commandChannelID string, summaryChannelID string) error) *MockGuildSettingsService_SetChannels_Call {
	_c.Call.Return(run)
	return _c
}

// SetRoleIDs provides a mock function for the type MockGuildSettingsService
func (_mock *MockGuildSettingsService) SetRoleIDs(ctx context.Context, guildID string, kind guildconfig.RoleKind, roleIDs []string) error {
	ret := _mock.Called(ctx, guildID, kind, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for SetRoleIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, guildconfig.RoleKind, []string) error); ok {
		r0 = returnFunc(ctx, guildID, kind, roleIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGuildSettingsService_SetRoleIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRoleIDs'
type MockGuildSettingsService_SetRoleIDs_Call struct {
	*mock.Call
}

// SetRoleIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - kind guildconfig.RoleKind
//   - roleIDs []string
func (_e *MockGuildSettingsService_Expecter) SetRoleIDs(ctx any, guildID any, kind any, roleIDs any) *MockGuildSettingsService_SetRoleIDs_Call {
	return &MockGuildSettingsService_SetRoleIDs_Call{Call: _e.mock.On("SetRoleIDs", ctx, guildID, kind, roleIDs)}
}

func (_c *MockGuildSettingsService_SetRoleIDs_Call) Run(run func(ctx context.Context, guildID string, kind guildconfig.RoleKind, roleIDs []string)) *MockGuildSettingsService_SetRoleIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 guildconfig.RoleKind
		if args[2] != nil {
			arg2 = args[2].(guildconfig.RoleKind)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGuildSettingsService_SetRoleIDs_Call) Return(err error) *MockGuildSettingsService_SetRoleIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGuildSettingsService_SetRoleIDs_Call) RunAndReturn(run func(ctx context.Context, guildID string, kind guildconfig.RoleKind, roleIDs []string) error) *MockGuildSettingsService_SetRoleIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SetWorld provides a mock function for the type MockGuildSettingsService
func (_mock *MockGuildSettingsService) SetWorld(ctx context.Context, guildID string, world string) error {
	ret := _mock.Called(ctx, guildID, world)

	if len(ret) == 0 {
		panic("no return value specified for SetWorld")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, guildID, world)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGuildSettingsService_SetWorld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorld'
type MockGuildSettingsService_SetWorld_Call struct {
	*mock.Call
}

// SetWorld is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - world string
func (_e *MockGuildSettingsService_Expecter) SetWorld(ctx any, guildID any, world any) *MockGuildSettingsService_SetWorld_Call {
	return &MockGuildSettingsService_SetWorld_Call{Call: _e.mock.On("SetWorld", ctx, guildID, world)}
}

func (_c *MockGuildSettingsService_SetWorld_Call) Run(run func(ctx context.Context, guildID string, world string)) *MockGuildSettingsService_SetWorld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGuildSettingsService_SetWorld_Call) Return(err error) *MockGuildSettingsService_SetWorld_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGuildSettingsService_SetWorld_Call) RunAndReturn(run func(ctx context.Context, guildID string, world string) error) *MockGuildSettingsService_SetWorld_Call {
	_c.Call.Return(run)
	return _c
}

// World provides a mock function for the type MockGuildSettingsService
func (_mock *MockGuildSettingsService) World(ctx context.Context, guildID string) (string, error) {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for World")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuildSettingsService_World_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'World'
type MockGuildSettingsService_World_Call struct {
	*mock.Call
}

// World is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockGuildSettingsService_Expecter) World(ctx any, guildID any) *MockGuildSettingsService_World_Call {
	return &MockGuildSettingsService_World_Call{Call: _e.mock.On("World", ctx, guildID)}
}

func (_c *MockGuildSettingsService_World_Call) Run(run func(ctx context.Context, guildID string)) *MockGuildSettingsService_World_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuildSettingsService_World_Call) Return(s string, err error) *MockGuildSettingsService_World_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGuildSettingsService_World_Call) RunAndReturn(run func(ctx context.Context, guildID string) (string, error)) *MockGuildSettingsService_World_Call {
	_c.Call.Return(run)
	return _c
}
