// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGuildActions creates a new instance of MockGuildActions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuildActions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuildActions {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGuildActions{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGuildActions is an autogenerated mock type for the GuildActions type
type MockGuildActions struct {
	mock.Mock
}

type MockGuildActions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuildActions) EXPECT() *MockGuildActions_Expecter {
	return &MockGuildActions_Expecter{mock: &_m.Mock}
}

// ApplyGuildConfig provides a mock function for the type MockGuildActions
func (_mock *MockGuildActions) ApplyGuildConfig(ctx context.Context, guildID string) {
	_mock.Called(ctx, guildID)
	return
}

// MockGuildActions_ApplyGuildConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyGuildConfig'
type MockGuildActions_ApplyGuildConfig_Call struct {
	*mock.Call
}

// ApplyGuildConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockGuildActions_Expecter) ApplyGuildConfig(ctx any, guildID any) *MockGuildActions_ApplyGuildConfig_Call {
	return &MockGuildActions_ApplyGuildConfig_Call{Call: _e.mock.On("ApplyGuildConfig", ctx, guildID)}
}

func (_c *MockGuildActions_ApplyGuildConfig_Call) Run(run func(ctx context.Context, guildID string)) *MockGuildActions_ApplyGuildConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuildActions_ApplyGuildConfig_Call) Return() *MockGuildActions_ApplyGuildConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGuildActions_ApplyGuildConfig_Call) RunAndReturn(run func(ctx context.Context, guildID string)) *MockGuildActions_ApplyGuildConfig_Call {
	_c.Run(run)
	return _c
}

// RefreshGuildLetter provides a mock function for the type MockGuildActions
func (_mock *MockGuildActions) RefreshGuildLetter(guildID string) {
	_mock.Called(guildID)
	return
}

// MockGuildActions_RefreshGuildLetter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshGuildLetter'
type MockGuildActions_RefreshGuildLetter_Call struct {
	*mock.Call
}

// RefreshGuildLetter is a helper method to define mock.On call
//   - guildID string
func (_e *MockGuildActions_Expecter) RefreshGuildLetter(guildID any) *MockGuildActions_RefreshGuildLetter_Call {
	return &MockGuildActions_RefreshGuildLetter_Call{Call: _e.mock.On("RefreshGuildLetter", guildID)}
}

func (_c *MockGuildActions_RefreshGuildLetter_Call) Run(run func(guildID string)) *MockGuildActions_RefreshGuildLetter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGuildActions_RefreshGuildLetter_Call) Return() *MockGuildActions_RefreshGuildLetter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGuildActions_RefreshGuildLetter_Call) RunAndReturn(run func(guildID string)) *MockGuildActions_RefreshGuildLetter_Call {
	_c.Run(run)
	return _c
}

// SyncGuild provides a mock function for the type MockGuildActions
func (_mock *MockGuildActions) SyncGuild(ctx context.Context, guildID string) error {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for SyncGuild")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGuildActions_SyncGuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncGuild'
type MockGuildActions_SyncGuild_Call struct {
	*mock.Call
}

// SyncGuild is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockGuildActions_Expecter) SyncGuild(ctx any, guildID any) *MockGuildActions_SyncGuild_Call {
	return &MockGuildActions_SyncGuild_Call{Call: _e.mock.On("SyncGuild", ctx, guildID)}
}

func (_c *MockGuildActions_SyncGuild_Call) Run(run func(ctx context.Context, guildID string)) *MockGuildActions_SyncGuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuildActions_SyncGuild_Call) Return(err error) *MockGuildActions_SyncGuild_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGuildActions_SyncGuild_Call) RunAndReturn(run func(ctx context.Context, guildID string) error) *MockGuildActions_SyncGuild_Call {
	_c.Call.Return(run)
	return _c
}
