// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/discord"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGuildChannelRepository creates a new instance of MockGuildChannelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuildChannelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuildChannelRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGuildChannelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGuildChannelRepository is an autogenerated mock type for the GuildChannelRepository type
type MockGuildChannelRepository struct {
	mock.Mock
}

type MockGuildChannelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuildChannelRepository) EXPECT() *MockGuildChannelRepository_Expecter {
	return &MockGuildChannelRepository_Expecter{mock: &_m.Mock}
}

// ListByTypes provides a mock function for the type MockGuildChannelRepository
func (_mock *MockGuildChannelRepository) ListByTypes(ctx context.Context, guildID string, types []discord.ChannelType) ([]*discord.Channel, error) {
	ret := _mock.Called(ctx, guildID, types)

	if len(ret) == 0 {
		panic("no return value specified for ListByTypes")
	}

	var r0 []*discord.Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []discord.ChannelType) ([]*discord.Channel, error)); ok {
		return returnFunc(ctx, guildID, types)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []discord.ChannelType) []*discord.Channel); ok {
		r0 = returnFunc(ctx, guildID, types)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*discord.Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []discord.ChannelType) error); ok {
		r1 = returnFunc(ctx, guildID, types)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuildChannelRepository_ListByTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTypes'
type MockGuildChannelRepository_ListByTypes_Call struct {
	*mock.Call
}

// ListByTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - types []discord.ChannelType
func (_e *MockGuildChannelRepository_Expecter) ListByTypes(ctx any, guildID any, types any) *MockGuildChannelRepository_ListByTypes_Call {
	return &MockGuildChannelRepository_ListByTypes_Call{Call: _e.mock.On("ListByTypes", ctx, guildID, types)}
}

func (_c *MockGuildChannelRepository_ListByTypes_Call) Run(run func(ctx context.Context, guildID string, types []discord.ChannelType)) *MockGuildChannelRepository_ListByTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []discord.ChannelType
		if args[2] != nil {
			arg2 = args[2].([]discord.ChannelType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGuildChannelRepository_ListByTypes_Call) Return(channels []*discord.Channel, err error) *MockGuildChannelRepository_ListByTypes_Call {
	_c.Call.Return(channels, err)
	return _c
}

func (_c *MockGuildChannelRepository_ListByTypes_Call) RunAndReturn(run func(ctx context.Context, guildID string, types []discord.ChannelType) ([]*discord.Channel, error)) *MockGuildChannelRepository_ListByTypes_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type MockGuildChannelRepository
func (_mock *MockGuildChannelRepository) Replace(ctx context.Context, guildID string, channels []*discord.Channel) error {
	ret := _mock.Called(ctx, guildID, channels)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*discord.Channel) error); ok {
		r0 = returnFunc(ctx, guildID, channels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGuildChannelRepository_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockGuildChannelRepository_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - channels []*discord.Channel
func (_e *MockGuildChannelRepository_Expecter) Replace(ctx any, guildID any, channels any) *MockGuildChannelRepository_Replace_Call {
	return &MockGuildChannelRepository_Replace_Call{Call: _e.mock.On("Replace", ctx, guildID, channels)}
}

func (_c *MockGuildChannelRepository_Replace_Call) Run(run func(ctx context.Context, guildID string, channels []*discord.Channel)) *MockGuildChannelRepository_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*discord.Channel
		if args[2] != nil {
			arg2 = args[2].([]*discord.Channel)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGuildChannelRepository_Replace_Call) Return(err error) *MockGuildChannelRepository_Replace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGuildChannelRepository_Replace_Call) RunAndReturn(run func(ctx context.Context, guildID string, channels []*discord.Channel) error) *MockGuildChannelRepository_Replace_Call {
	_c.Call.Return(run)
	return _c
}
