// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/access"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGuildAccessService creates a new instance of MockGuildAccessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGuildAccessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGuildAccessService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGuildAccessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGuildAccessService is an autogenerated mock type for the GuildAccessService type
type MockGuildAccessService struct {
	mock.Mock
}

type MockGuildAccessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGuildAccessService) EXPECT() *MockGuildAccessService_Expecter {
	return &MockGuildAccessService_Expecter{mock: &_m.Mock}
}

// Access provides a mock function for the type MockGuildAccessService
func (_mock *MockGuildAccessService) Access(ctx context.Context, userID string, guildID string) (*access.GuildAccess, error) {
	ret := _mock.Called(ctx, userID, guildID)

	if len(ret) == 0 {
		panic("no return value specified for Access")
	}

	var r0 *access.GuildAccess
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*access.GuildAccess, error)); ok {
		return returnFunc(ctx, userID, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *access.GuildAccess); ok {
		r0 = returnFunc(ctx, userID, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.GuildAccess)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuildAccessService_Access_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Access'
type MockGuildAccessService_Access_Call struct {
	*mock.Call
}

// Access is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - guildID string
func (_e *MockGuildAccessService_Expecter) Access(ctx any, userID any, guildID any) *MockGuildAccessService_Access_Call {
	return &MockGuildAccessService_Access_Call{Call: _e.mock.On("Access", ctx, userID, guildID)}
}

func (_c *MockGuildAccessService_Access_Call) Run(run func(ctx context.Context, userID string, guildID string)) *MockGuildAccessService_Access_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGuildAccessService_Access_Call) Return(guildAccess *access.GuildAccess, err error) *MockGuildAccessService_Access_Call {
	_c.Call.Return(guildAccess, err)
	return _c
}

func (_c *MockGuildAccessService_Access_Call) RunAndReturn(run func(ctx context.Context, userID string, guildID string) (*access.GuildAccess, error)) *MockGuildAccessService_Access_Call {
	_c.Call.Return(run)
	return _c
}

// AccessibleGuilds provides a mock function for the type MockGuildAccessService
func (_mock *MockGuildAccessService) AccessibleGuilds(ctx context.Context, userID string) ([]access.GuildAccess, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AccessibleGuilds")
	}

	var r0 []access.GuildAccess
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]access.GuildAccess, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []access.GuildAccess); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]access.GuildAccess)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuildAccessService_AccessibleGuilds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessibleGuilds'
type MockGuildAccessService_AccessibleGuilds_Call struct {
	*mock.Call
}

// AccessibleGuilds is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockGuildAccessService_Expecter) AccessibleGuilds(ctx any, userID any) *MockGuildAccessService_AccessibleGuilds_Call {
	return &MockGuildAccessService_AccessibleGuilds_Call{Call: _e.mock.On("AccessibleGuilds", ctx, userID)}
}

func (_c *MockGuildAccessService_AccessibleGuilds_Call) Run(run func(ctx context.Context, userID string)) *MockGuildAccessService_AccessibleGuilds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGuildAccessService_AccessibleGuilds_Call) Return(guildAccesss []access.GuildAccess, err error) *MockGuildAccessService_AccessibleGuilds_Call {
	_c.Call.Return(guildAccesss, err)
	return _c
}

func (_c *MockGuildAccessService_AccessibleGuilds_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]access.GuildAccess, error)) *MockGuildAccessService_AccessibleGuilds_Call {
	_c.Call.Return(run)
	return _c
}

// IsSiteAdmin provides a mock function for the type MockGuildAccessService
func (_mock *MockGuildAccessService) IsSiteAdmin(userID string) bool {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for IsSiteAdmin")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGuildAccessService_IsSiteAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSiteAdmin'
type MockGuildAccessService_IsSiteAdmin_Call struct {
	*mock.Call
}

// IsSiteAdmin is a helper method to define mock.On call
//   - userID string
func (_e *MockGuildAccessService_Expecter) IsSiteAdmin(userID any) *MockGuildAccessService_IsSiteAdmin_Call {
	return &MockGuildAccessService_IsSiteAdmin_Call{Call: _e.mock.On("IsSiteAdmin", userID)}
}

func (_c *MockGuildAccessService_IsSiteAdmin_Call) Run(run func(userID string)) *MockGuildAccessService_IsSiteAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGuildAccessService_IsSiteAdmin_Call) Return(b bool) *MockGuildAccessService_IsSiteAdmin_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGuildAccessService_IsSiteAdmin_Call) RunAndReturn(run func(userID string) bool) *MockGuildAccessService_IsSiteAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// Member provides a mock function for the type MockGuildAccessService
func (_mock *MockGuildAccessService) Member(ctx context.Context, userID string, guildID string) (*access.GuildMember, error) {
	ret := _mock.Called(ctx, userID, guildID)

	if len(ret) == 0 {
		panic("no return value specified for Member")
	}

	var r0 *access.GuildMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*access.GuildMember, error)); ok {
		return returnFunc(ctx, userID, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *access.GuildMember); ok {
		r0 = returnFunc(ctx, userID, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.GuildMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGuildAccessService_Member_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Member'
type MockGuildAccessService_Member_Call struct {
	*mock.Call
}

// Member is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - guildID string
func (_e *MockGuildAccessService_Expecter) Member(ctx any, userID any, guildID any) *MockGuildAccessService_Member_Call {
	return &MockGuildAccessService_Member_Call{Call: _e.mock.On("Member", ctx, userID, guildID)}
}

func (_c *MockGuildAccessService_Member_Call) Run(run func(ctx context.Context, userID string, guildID string)) *MockGuildAccessService_Member_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGuildAccessService_Member_Call) Return(guildMember *access.GuildMember, err error) *MockGuildAccessService_Member_Call {
	_c.Call.Return(guildMember, err)
	return _c
}

func (_c *MockGuildAccessService_Member_Call) RunAndReturn(run func(ctx context.Context, userID string, guildID string) (*access.GuildMember, error)) *MockGuildAccessService_Member_Call {
	_c.Call.Return(run)
	return _c
}
