// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJobLocker creates a new instance of MockJobLocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobLocker {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockJobLocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockJobLocker is an autogenerated mock type for the JobLocker type
type MockJobLocker struct {
	mock.Mock
}

type MockJobLocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobLocker) EXPECT() *MockJobLocker_Expecter {
	return &MockJobLocker_Expecter{mock: &_m.Mock}
}

// TryLock provides a mock function for the type MockJobLocker
func (_mock *MockJobLocker) TryLock(ctx context.Context) (func(), bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TryLock")
	}

	var r0 func()
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (func(), bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) func()); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockJobLocker_TryLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryLock'
type MockJobLocker_TryLock_Call struct {
	*mock.Call
}

// TryLock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJobLocker_Expecter) TryLock(ctx any) *MockJobLocker_TryLock_Call {
	return &MockJobLocker_TryLock_Call{Call: _e.mock.On("TryLock", ctx)}
}

func (_c *MockJobLocker_TryLock_Call) Run(run func(ctx context.Context)) *MockJobLocker_TryLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobLocker_TryLock_Call) Return(unlock func(), ok bool, err error) *MockJobLocker_TryLock_Call {
	_c.Call.Return(unlock, ok, err)
	return _c
}

func (_c *MockJobLocker_TryLock_Call) RunAndReturn(run func(ctx context.Context) (func(), bool, error)) *MockJobLocker_TryLock_Call {
	_c.Call.Return(run)
	return _c
}
