// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"spot-assistant/internal/core/dto/guild"
	"spot-assistant/internal/core/dto/member"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMemberRepository creates a new instance of MockMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMemberRepository is an autogenerated mock type for the MemberRepository type
type MockMemberRepository struct {
	mock.Mock
}

type MockMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberRepository) EXPECT() *MockMemberRepository_Expecter {
	return &MockMemberRepository_Expecter{mock: &_m.Mock}
}

// GetMemberByGuildAndID provides a mock function for the type MockMemberRepository
func (_mock *MockMemberRepository) GetMemberByGuildAndID(g *guild.Guild, memberID string) (*member.Member, error) {
	ret := _mock.Called(g, memberID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberByGuildAndID")
	}

	var r0 *member.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*guild.Guild, string) (*member.Member, error)); ok {
		return returnFunc(g, memberID)
	}
	if returnFunc, ok := ret.Get(0).(func(*guild.Guild, string) *member.Member); ok {
		r0 = returnFunc(g, memberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*member.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*guild.Guild, string) error); ok {
		r1 = returnFunc(g, memberID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMemberRepository_GetMemberByGuildAndID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberByGuildAndID'
type MockMemberRepository_GetMemberByGuildAndID_Call struct {
	*mock.Call
}

// GetMemberByGuildAndID is a helper method to define mock.On call
//   - g *guild.Guild
//   - memberID string
func (_e *MockMemberRepository_Expecter) GetMemberByGuildAndID(g any, memberID any) *MockMemberRepository_GetMemberByGuildAndID_Call {
	return &MockMemberRepository_GetMemberByGuildAndID_Call{Call: _e.mock.On("GetMemberByGuildAndID", g, memberID)}
}

func (_c *MockMemberRepository_GetMemberByGuildAndID_Call) Run(run func(g *guild.Guild, memberID string)) *MockMemberRepository_GetMemberByGuildAndID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *guild.Guild
		if args[0] != nil {
			arg0 = args[0].(*guild.Guild)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMemberRepository_GetMemberByGuildAndID_Call) Return(member1 *member.Member, err error) *MockMemberRepository_GetMemberByGuildAndID_Call {
	_c.Call.Return(member1, err)
	return _c
}

func (_c *MockMemberRepository_GetMemberByGuildAndID_Call) RunAndReturn(run func(g *guild.Guild, memberID string) (*member.Member, error)) *MockMemberRepository_GetMemberByGuildAndID_Call {
	_c.Call.Return(run)
	return _c
}
