// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifyHandler creates a new instance of MockNotifyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifyHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifyHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockNotifyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockNotifyHandler is an autogenerated mock type for the NotifyHandler type
type MockNotifyHandler struct {
	mock.Mock
}

type MockNotifyHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifyHandler) EXPECT() *MockNotifyHandler_Expecter {
	return &MockNotifyHandler_Expecter{mock: &_m.Mock}
}

// OnGuildConfig provides a mock function for the type MockNotifyHandler
func (_mock *MockNotifyHandler) OnGuildConfig(ctx context.Context, guildID string) {
	_mock.Called(ctx, guildID)
	return
}

// MockNotifyHandler_OnGuildConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnGuildConfig'
type MockNotifyHandler_OnGuildConfig_Call struct {
	*mock.Call
}

// OnGuildConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockNotifyHandler_Expecter) OnGuildConfig(ctx any, guildID any) *MockNotifyHandler_OnGuildConfig_Call {
	return &MockNotifyHandler_OnGuildConfig_Call{Call: _e.mock.On("OnGuildConfig", ctx, guildID)}
}

func (_c *MockNotifyHandler_OnGuildConfig_Call) Run(run func(ctx context.Context, guildID string)) *MockNotifyHandler_OnGuildConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifyHandler_OnGuildConfig_Call) Return() *MockNotifyHandler_OnGuildConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifyHandler_OnGuildConfig_Call) RunAndReturn(run func(ctx context.Context, guildID string)) *MockNotifyHandler_OnGuildConfig_Call {
	_c.Run(run)
	return _c
}

// OnGuildResync provides a mock function for the type MockNotifyHandler
func (_mock *MockNotifyHandler) OnGuildResync(ctx context.Context, guildID string) {
	_mock.Called(ctx, guildID)
	return
}

// MockNotifyHandler_OnGuildResync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnGuildResync'
type MockNotifyHandler_OnGuildResync_Call struct {
	*mock.Call
}

// OnGuildResync is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockNotifyHandler_Expecter) OnGuildResync(ctx any, guildID any) *MockNotifyHandler_OnGuildResync_Call {
	return &MockNotifyHandler_OnGuildResync_Call{Call: _e.mock.On("OnGuildResync", ctx, guildID)}
}

func (_c *MockNotifyHandler_OnGuildResync_Call) Run(run func(ctx context.Context, guildID string)) *MockNotifyHandler_OnGuildResync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifyHandler_OnGuildResync_Call) Return() *MockNotifyHandler_OnGuildResync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifyHandler_OnGuildResync_Call) RunAndReturn(run func(ctx context.Context, guildID string)) *MockNotifyHandler_OnGuildResync_Call {
	_c.Run(run)
	return _c
}

// OnOverbooked provides a mock function for the type MockNotifyHandler
func (_mock *MockNotifyHandler) OnOverbooked(ctx context.Context, payload []byte) {
	_mock.Called(ctx, payload)
	return
}

// MockNotifyHandler_OnOverbooked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnOverbooked'
type MockNotifyHandler_OnOverbooked_Call struct {
	*mock.Call
}

// OnOverbooked is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *MockNotifyHandler_Expecter) OnOverbooked(ctx any, payload any) *MockNotifyHandler_OnOverbooked_Call {
	return &MockNotifyHandler_OnOverbooked_Call{Call: _e.mock.On("OnOverbooked", ctx, payload)}
}

func (_c *MockNotifyHandler_OnOverbooked_Call) Run(run func(ctx context.Context, payload []byte)) *MockNotifyHandler_OnOverbooked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifyHandler_OnOverbooked_Call) Return() *MockNotifyHandler_OnOverbooked_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifyHandler_OnOverbooked_Call) RunAndReturn(run func(ctx context.Context, payload []byte)) *MockNotifyHandler_OnOverbooked_Call {
	_c.Run(run)
	return _c
}

// OnSummaryRefresh provides a mock function for the type MockNotifyHandler
func (_mock *MockNotifyHandler) OnSummaryRefresh(ctx context.Context, guildID string) {
	_mock.Called(ctx, guildID)
	return
}

// MockNotifyHandler_OnSummaryRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnSummaryRefresh'
type MockNotifyHandler_OnSummaryRefresh_Call struct {
	*mock.Call
}

// OnSummaryRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *MockNotifyHandler_Expecter) OnSummaryRefresh(ctx any, guildID any) *MockNotifyHandler_OnSummaryRefresh_Call {
	return &MockNotifyHandler_OnSummaryRefresh_Call{Call: _e.mock.On("OnSummaryRefresh", ctx, guildID)}
}

func (_c *MockNotifyHandler_OnSummaryRefresh_Call) Run(run func(ctx context.Context, guildID string)) *MockNotifyHandler_OnSummaryRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifyHandler_OnSummaryRefresh_Call) Return() *MockNotifyHandler_OnSummaryRefresh_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotifyHandler_OnSummaryRefresh_Call) RunAndReturn(run func(ctx context.Context, guildID string)) *MockNotifyHandler_OnSummaryRefresh_Call {
	_c.Run(run)
	return _c
}
