// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifyExecutor creates a new instance of MockNotifyExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifyExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifyExecutor {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockNotifyExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockNotifyExecutor is an autogenerated mock type for the NotifyExecutor type
type MockNotifyExecutor struct {
	mock.Mock
}

type MockNotifyExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifyExecutor) EXPECT() *MockNotifyExecutor_Expecter {
	return &MockNotifyExecutor_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockNotifyExecutor
func (_mock *MockNotifyExecutor) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(arguments) > 0 {
		tmpRet = _mock.Called(ctx, sql, arguments)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, arguments...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotifyExecutor_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockNotifyExecutor_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...any
func (_e *MockNotifyExecutor_Expecter) Exec(ctx any, sql any, arguments ...any) *MockNotifyExecutor_Exec_Call {
	return &MockNotifyExecutor_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{ctx, sql}, arguments...)...)}
}

func (_c *MockNotifyExecutor_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...any)) *MockNotifyExecutor_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotifyExecutor_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockNotifyExecutor_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockNotifyExecutor_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)) *MockNotifyExecutor_Exec_Call {
	_c.Call.Return(run)
	return _c
}
