// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/access"
	"spot-assistant/internal/core/dto/webuser"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOAuthPort creates a new instance of MockOAuthPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthPort {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOAuthPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOAuthPort is an autogenerated mock type for the OAuthPort type
type MockOAuthPort struct {
	mock.Mock
}

type MockOAuthPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthPort) EXPECT() *MockOAuthPort_Expecter {
	return &MockOAuthPort_Expecter{mock: &_m.Mock}
}

// AuthCodeURL provides a mock function for the type MockOAuthPort
func (_mock *MockOAuthPort) AuthCodeURL(state string) string {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOAuthPort_AuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthCodeURL'
type MockOAuthPort_AuthCodeURL_Call struct {
	*mock.Call
}

// AuthCodeURL is a helper method to define mock.On call
//   - state string
func (_e *MockOAuthPort_Expecter) AuthCodeURL(state any) *MockOAuthPort_AuthCodeURL_Call {
	return &MockOAuthPort_AuthCodeURL_Call{Call: _e.mock.On("AuthCodeURL", state)}
}

func (_c *MockOAuthPort_AuthCodeURL_Call) Run(run func(state string)) *MockOAuthPort_AuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOAuthPort_AuthCodeURL_Call) Return(s string) *MockOAuthPort_AuthCodeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOAuthPort_AuthCodeURL_Call) RunAndReturn(run func(state string) string) *MockOAuthPort_AuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type MockOAuthPort
func (_mock *MockOAuthPort) Exchange(ctx context.Context, code string) (*webuser.User, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *webuser.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*webuser.User, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *webuser.User); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webuser.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthPort_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockOAuthPort_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockOAuthPort_Expecter) Exchange(ctx any, code any) *MockOAuthPort_Exchange_Call {
	return &MockOAuthPort_Exchange_Call{Call: _e.mock.On("Exchange", ctx, code)}
}

func (_c *MockOAuthPort_Exchange_Call) Run(run func(ctx context.Context, code string)) *MockOAuthPort_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOAuthPort_Exchange_Call) Return(user *webuser.User, err error) *MockOAuthPort_Exchange_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockOAuthPort_Exchange_Call) RunAndReturn(run func(ctx context.Context, code string) (*webuser.User, error)) *MockOAuthPort_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// UserGuildMember provides a mock function for the type MockOAuthPort
func (_mock *MockOAuthPort) UserGuildMember(ctx context.Context, userID string, guildID string) (*access.GuildMember, error) {
	ret := _mock.Called(ctx, userID, guildID)

	if len(ret) == 0 {
		panic("no return value specified for UserGuildMember")
	}

	var r0 *access.GuildMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*access.GuildMember, error)); ok {
		return returnFunc(ctx, userID, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *access.GuildMember); ok {
		r0 = returnFunc(ctx, userID, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*access.GuildMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthPort_UserGuildMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGuildMember'
type MockOAuthPort_UserGuildMember_Call struct {
	*mock.Call
}

// UserGuildMember is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - guildID string
func (_e *MockOAuthPort_Expecter) UserGuildMember(ctx any, userID any, guildID any) *MockOAuthPort_UserGuildMember_Call {
	return &MockOAuthPort_UserGuildMember_Call{Call: _e.mock.On("UserGuildMember", ctx, userID, guildID)}
}

func (_c *MockOAuthPort_UserGuildMember_Call) Run(run func(ctx context.Context, userID string, guildID string)) *MockOAuthPort_UserGuildMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOAuthPort_UserGuildMember_Call) Return(guildMember *access.GuildMember, err error) *MockOAuthPort_UserGuildMember_Call {
	_c.Call.Return(guildMember, err)
	return _c
}

func (_c *MockOAuthPort_UserGuildMember_Call) RunAndReturn(run func(ctx context.Context, userID string, guildID string) (*access.GuildMember, error)) *MockOAuthPort_UserGuildMember_Call {
	_c.Call.Return(run)
	return _c
}

// UserGuilds provides a mock function for the type MockOAuthPort
func (_mock *MockOAuthPort) UserGuilds(ctx context.Context, userID string) ([]access.UserGuild, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserGuilds")
	}

	var r0 []access.UserGuild
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]access.UserGuild, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []access.UserGuild); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]access.UserGuild)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthPort_UserGuilds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserGuilds'
type MockOAuthPort_UserGuilds_Call struct {
	*mock.Call
}

// UserGuilds is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockOAuthPort_Expecter) UserGuilds(ctx any, userID any) *MockOAuthPort_UserGuilds_Call {
	return &MockOAuthPort_UserGuilds_Call{Call: _e.mock.On("UserGuilds", ctx, userID)}
}

func (_c *MockOAuthPort_UserGuilds_Call) Run(run func(ctx context.Context, userID string)) *MockOAuthPort_UserGuilds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOAuthPort_UserGuilds_Call) Return(userGuilds []access.UserGuild, err error) *MockOAuthPort_UserGuilds_Call {
	_c.Call.Return(userGuilds, err)
	return _c
}

func (_c *MockOAuthPort_UserGuilds_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]access.UserGuild, error)) *MockOAuthPort_UserGuilds_Call {
	_c.Call.Return(run)
	return _c
}
