// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"spot-assistant/internal/core/dto/summary"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOnlineCheckService creates a new instance of MockOnlineCheckService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnlineCheckService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnlineCheckService {
	mock := &MockOnlineCheckService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOnlineCheckService is an autogenerated mock type for the OnlineCheckService type
type MockOnlineCheckService struct {
	mock.Mock
}

type MockOnlineCheckService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnlineCheckService) EXPECT() *MockOnlineCheckService_Expecter {
	return &MockOnlineCheckService_Expecter{mock: &_m.Mock}
}

// ConfigureWorldName provides a mock function for the type MockOnlineCheckService
func (_mock *MockOnlineCheckService) ConfigureWorldName(guildID string, world string) {
	_mock.Called(guildID, world)
	return
}

// MockOnlineCheckService_ConfigureWorldName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureWorldName'
type MockOnlineCheckService_ConfigureWorldName_Call struct {
	*mock.Call
}

// ConfigureWorldName is a helper method to define mock.On call
//   - guildID string
//   - world string
func (_e *MockOnlineCheckService_Expecter) ConfigureWorldName(guildID interface{}, world interface{}) *MockOnlineCheckService_ConfigureWorldName_Call {
	return &MockOnlineCheckService_ConfigureWorldName_Call{Call: _e.mock.On("ConfigureWorldName", guildID, world)}
}

func (_c *MockOnlineCheckService_ConfigureWorldName_Call) Run(run func(guildID string, world string)) *MockOnlineCheckService_ConfigureWorldName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOnlineCheckService_ConfigureWorldName_Call) Return() *MockOnlineCheckService_ConfigureWorldName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnlineCheckService_ConfigureWorldName_Call) RunAndReturn(run func(guildID string, world string)) *MockOnlineCheckService_ConfigureWorldName_Call {
	_c.Run(run)
	return _c
}

// ConfigureWorldNameForGuild provides a mock function for the type MockOnlineCheckService
func (_mock *MockOnlineCheckService) ConfigureWorldNameForGuild(guildID string) error {
	ret := _mock.Called(guildID)

	if len(ret) == 0 {
		panic("no return value specified for ConfigureWorldNameForGuild")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(guildID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOnlineCheckService_ConfigureWorldNameForGuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureWorldNameForGuild'
type MockOnlineCheckService_ConfigureWorldNameForGuild_Call struct {
	*mock.Call
}

// ConfigureWorldNameForGuild is a helper method to define mock.On call
//   - guildID string
func (_e *MockOnlineCheckService_Expecter) ConfigureWorldNameForGuild(guildID interface{}) *MockOnlineCheckService_ConfigureWorldNameForGuild_Call {
	return &MockOnlineCheckService_ConfigureWorldNameForGuild_Call{Call: _e.mock.On("ConfigureWorldNameForGuild", guildID)}
}

func (_c *MockOnlineCheckService_ConfigureWorldNameForGuild_Call) Run(run func(guildID string)) *MockOnlineCheckService_ConfigureWorldNameForGuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOnlineCheckService_ConfigureWorldNameForGuild_Call) Return(err error) *MockOnlineCheckService_ConfigureWorldNameForGuild_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOnlineCheckService_ConfigureWorldNameForGuild_Call) RunAndReturn(run func(guildID string) error) *MockOnlineCheckService_ConfigureWorldNameForGuild_Call {
	_c.Call.Return(run)
	return _c
}

// IsConfigured provides a mock function for the type MockOnlineCheckService
func (_mock *MockOnlineCheckService) IsConfigured() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConfigured")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockOnlineCheckService_IsConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConfigured'
type MockOnlineCheckService_IsConfigured_Call struct {
	*mock.Call
}

// IsConfigured is a helper method to define mock.On call
func (_e *MockOnlineCheckService_Expecter) IsConfigured() *MockOnlineCheckService_IsConfigured_Call {
	return &MockOnlineCheckService_IsConfigured_Call{Call: _e.mock.On("IsConfigured")}
}

func (_c *MockOnlineCheckService_IsConfigured_Call) Run(run func()) *MockOnlineCheckService_IsConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnlineCheckService_IsConfigured_Call) Return(b bool) *MockOnlineCheckService_IsConfigured_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockOnlineCheckService_IsConfigured_Call) RunAndReturn(run func() bool) *MockOnlineCheckService_IsConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// IsOnline provides a mock function for the type MockOnlineCheckService
func (_mock *MockOnlineCheckService) IsOnline(guildID string, characterName string) bool {
	ret := _mock.Called(guildID, characterName)

	if len(ret) == 0 {
		panic("no return value specified for IsOnline")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(guildID, characterName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockOnlineCheckService_IsOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOnline'
type MockOnlineCheckService_IsOnline_Call struct {
	*mock.Call
}

// IsOnline is a helper method to define mock.On call
//   - guildID string
//   - characterName string
func (_e *MockOnlineCheckService_Expecter) IsOnline(guildID interface{}, characterName interface{}) *MockOnlineCheckService_IsOnline_Call {
	return &MockOnlineCheckService_IsOnline_Call{Call: _e.mock.On("IsOnline", guildID, characterName)}
}

func (_c *MockOnlineCheckService_IsOnline_Call) Run(run func(guildID string, characterName string)) *MockOnlineCheckService_IsOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOnlineCheckService_IsOnline_Call) Return(b bool) *MockOnlineCheckService_IsOnline_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockOnlineCheckService_IsOnline_Call) RunAndReturn(run func(guildID string, characterName string) bool) *MockOnlineCheckService_IsOnline_Call {
	_c.Call.Return(run)
	return _c
}

// PlayerStatus provides a mock function for the type MockOnlineCheckService
func (_mock *MockOnlineCheckService) PlayerStatus(guildID string, characterName string) summary.OnlineStatus {
	ret := _mock.Called(guildID, characterName)

	if len(ret) == 0 {
		panic("no return value specified for PlayerStatus")
	}

	var r0 summary.OnlineStatus
	if returnFunc, ok := ret.Get(0).(func(string, string) summary.OnlineStatus); ok {
		r0 = returnFunc(guildID, characterName)
	} else {
		r0 = ret.Get(0).(summary.OnlineStatus)
	}
	return r0
}

// MockOnlineCheckService_PlayerStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlayerStatus'
type MockOnlineCheckService_PlayerStatus_Call struct {
	*mock.Call
}

// PlayerStatus is a helper method to define mock.On call
//   - guildID string
//   - characterName string
func (_e *MockOnlineCheckService_Expecter) PlayerStatus(guildID interface{}, characterName interface{}) *MockOnlineCheckService_PlayerStatus_Call {
	return &MockOnlineCheckService_PlayerStatus_Call{Call: _e.mock.On("PlayerStatus", guildID, characterName)}
}

func (_c *MockOnlineCheckService_PlayerStatus_Call) Run(run func(guildID string, characterName string)) *MockOnlineCheckService_PlayerStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOnlineCheckService_PlayerStatus_Call) Return(onlineStatus summary.OnlineStatus) *MockOnlineCheckService_PlayerStatus_Call {
	_c.Call.Return(onlineStatus)
	return _c
}

func (_c *MockOnlineCheckService_PlayerStatus_Call) RunAndReturn(run func(guildID string, characterName string) summary.OnlineStatus) *MockOnlineCheckService_PlayerStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshOnlinePlayers provides a mock function for the type MockOnlineCheckService
func (_mock *MockOnlineCheckService) RefreshOnlinePlayers(guildID string) error {
	ret := _mock.Called(guildID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshOnlinePlayers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(guildID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOnlineCheckService_RefreshOnlinePlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshOnlinePlayers'
type MockOnlineCheckService_RefreshOnlinePlayers_Call struct {
	*mock.Call
}

// RefreshOnlinePlayers is a helper method to define mock.On call
//   - guildID string
func (_e *MockOnlineCheckService_Expecter) RefreshOnlinePlayers(guildID interface{}) *MockOnlineCheckService_RefreshOnlinePlayers_Call {
	return &MockOnlineCheckService_RefreshOnlinePlayers_Call{Call: _e.mock.On("RefreshOnlinePlayers", guildID)}
}

func (_c *MockOnlineCheckService_RefreshOnlinePlayers_Call) Run(run func(guildID string)) *MockOnlineCheckService_RefreshOnlinePlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOnlineCheckService_RefreshOnlinePlayers_Call) Return(err error) *MockOnlineCheckService_RefreshOnlinePlayers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOnlineCheckService_RefreshOnlinePlayers_Call) RunAndReturn(run func(guildID string) error) *MockOnlineCheckService_RefreshOnlinePlayers_Call {
	_c.Call.Return(run)
	return _c
}

// SetGuildWorld provides a mock function for the type MockOnlineCheckService
func (_mock *MockOnlineCheckService) SetGuildWorld(guildID string, world string) error {
	ret := _mock.Called(guildID, world)

	if len(ret) == 0 {
		panic("no return value specified for SetGuildWorld")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(guildID, world)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOnlineCheckService_SetGuildWorld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGuildWorld'
type MockOnlineCheckService_SetGuildWorld_Call struct {
	*mock.Call
}

// SetGuildWorld is a helper method to define mock.On call
//   - guildID string
//   - world string
func (_e *MockOnlineCheckService_Expecter) SetGuildWorld(guildID interface{}, world interface{}) *MockOnlineCheckService_SetGuildWorld_Call {
	return &MockOnlineCheckService_SetGuildWorld_Call{Call: _e.mock.On("SetGuildWorld", guildID, world)}
}

func (_c *MockOnlineCheckService_SetGuildWorld_Call) Run(run func(guildID string, world string)) *MockOnlineCheckService_SetGuildWorld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOnlineCheckService_SetGuildWorld_Call) Return(err error) *MockOnlineCheckService_SetGuildWorld_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOnlineCheckService_SetGuildWorld_Call) RunAndReturn(run func(guildID string, world string) error) *MockOnlineCheckService_SetGuildWorld_Call {
	_c.Call.Return(run)
	return _c
}

// TryRefresh provides a mock function for the type MockOnlineCheckService
func (_mock *MockOnlineCheckService) TryRefresh(guildID string) {
	_mock.Called(guildID)
	return
}

// MockOnlineCheckService_TryRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryRefresh'
type MockOnlineCheckService_TryRefresh_Call struct {
	*mock.Call
}

// TryRefresh is a helper method to define mock.On call
//   - guildID string
func (_e *MockOnlineCheckService_Expecter) TryRefresh(guildID interface{}) *MockOnlineCheckService_TryRefresh_Call {
	return &MockOnlineCheckService_TryRefresh_Call{Call: _e.mock.On("TryRefresh", guildID)}
}

func (_c *MockOnlineCheckService_TryRefresh_Call) Run(run func(guildID string)) *MockOnlineCheckService_TryRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOnlineCheckService_TryRefresh_Call) Return() *MockOnlineCheckService_TryRefresh_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnlineCheckService_TryRefresh_Call) RunAndReturn(run func(guildID string)) *MockOnlineCheckService_TryRefresh_Call {
	_c.Run(run)
	return _c
}
