// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/guildconfig"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPremiumService creates a new instance of MockPremiumService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPremiumService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPremiumService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPremiumService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPremiumService is an autogenerated mock type for the PremiumService type
type MockPremiumService struct {
	mock.Mock
}

type MockPremiumService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPremiumService) EXPECT() *MockPremiumService_Expecter {
	return &MockPremiumService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockPremiumService
func (_mock *MockPremiumService) List(ctx context.Context) ([]*guildconfig.Config, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*guildconfig.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*guildconfig.Config, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*guildconfig.Config); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*guildconfig.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPremiumService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPremiumService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPremiumService_Expecter) List(ctx any) *MockPremiumService_List_Call {
	return &MockPremiumService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockPremiumService_List_Call) Run(run func(ctx context.Context)) *MockPremiumService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPremiumService_List_Call) Return(configs []*guildconfig.Config, err error) *MockPremiumService_List_Call {
	_c.Call.Return(configs, err)
	return _c
}

func (_c *MockPremiumService_List_Call) RunAndReturn(run func(ctx context.Context) ([]*guildconfig.Config, error)) *MockPremiumService_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetPremium provides a mock function for the type MockPremiumService
func (_mock *MockPremiumService) SetPremium(ctx context.Context, guildID string, premium bool) error {
	ret := _mock.Called(ctx, guildID, premium)

	if len(ret) == 0 {
		panic("no return value specified for SetPremium")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, guildID, premium)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPremiumService_SetPremium_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPremium'
type MockPremiumService_SetPremium_Call struct {
	*mock.Call
}

// SetPremium is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - premium bool
func (_e *MockPremiumService_Expecter) SetPremium(ctx any, guildID any, premium any) *MockPremiumService_SetPremium_Call {
	return &MockPremiumService_SetPremium_Call{Call: _e.mock.On("SetPremium", ctx, guildID, premium)}
}

func (_c *MockPremiumService_SetPremium_Call) Run(run func(ctx context.Context, guildID string, premium bool)) *MockPremiumService_SetPremium_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPremiumService_SetPremium_Call) Return(err error) *MockPremiumService_SetPremium_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPremiumService_SetPremium_Call) RunAndReturn(run func(ctx context.Context, guildID string, premium bool) error) *MockPremiumService_SetPremium_Call {
	_c.Call.Return(run)
	return _c
}
