// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/reservation"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReservationFormService creates a new instance of MockReservationFormService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationFormService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationFormService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReservationFormService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReservationFormService is an autogenerated mock type for the ReservationFormService type
type MockReservationFormService struct {
	mock.Mock
}

type MockReservationFormService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationFormService) EXPECT() *MockReservationFormService_Expecter {
	return &MockReservationFormService_Expecter{mock: &_m.Mock}
}

// Book provides a mock function for the type MockReservationFormService
func (_mock *MockReservationFormService) Book(ctx context.Context, guildID string, actor reservation.Actor, draft reservation.Draft) (*reservation.FormOutcome, error) {
	ret := _mock.Called(ctx, guildID, actor, draft)

	if len(ret) == 0 {
		panic("no return value specified for Book")
	}

	var r0 *reservation.FormOutcome
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, reservation.Draft) (*reservation.FormOutcome, error)); ok {
		return returnFunc(ctx, guildID, actor, draft)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, reservation.Draft) *reservation.FormOutcome); ok {
		r0 = returnFunc(ctx, guildID, actor, draft)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.FormOutcome)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, reservation.Actor, reservation.Draft) error); ok {
		r1 = returnFunc(ctx, guildID, actor, draft)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationFormService_Book_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Book'
type MockReservationFormService_Book_Call struct {
	*mock.Call
}

// Book is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - actor reservation.Actor
//   - draft reservation.Draft
func (_e *MockReservationFormService_Expecter) Book(ctx any, guildID any, actor any, draft any) *MockReservationFormService_Book_Call {
	return &MockReservationFormService_Book_Call{Call: _e.mock.On("Book", ctx, guildID, actor, draft)}
}

func (_c *MockReservationFormService_Book_Call) Run(run func(ctx context.Context, guildID string, actor reservation.Actor, draft reservation.Draft)) *MockReservationFormService_Book_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 reservation.Actor
		if args[2] != nil {
			arg2 = args[2].(reservation.Actor)
		}
		var arg3 reservation.Draft
		if args[3] != nil {
			arg3 = args[3].(reservation.Draft)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReservationFormService_Book_Call) Return(formOutcome *reservation.FormOutcome, err error) *MockReservationFormService_Book_Call {
	_c.Call.Return(formOutcome, err)
	return _c
}

func (_c *MockReservationFormService_Book_Call) RunAndReturn(run func(ctx context.Context, guildID string, actor reservation.Actor, draft reservation.Draft) (*reservation.FormOutcome, error)) *MockReservationFormService_Book_Call {
	_c.Call.Return(run)
	return _c
}

// BookForm provides a mock function for the type MockReservationFormService
func (_mock *MockReservationFormService) BookForm(ctx context.Context, guildID string, actor reservation.Actor, form reservation.Form) (*reservation.FormOutcome, error) {
	ret := _mock.Called(ctx, guildID, actor, form)

	if len(ret) == 0 {
		panic("no return value specified for BookForm")
	}

	var r0 *reservation.FormOutcome
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, reservation.Form) (*reservation.FormOutcome, error)); ok {
		return returnFunc(ctx, guildID, actor, form)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, reservation.Form) *reservation.FormOutcome); ok {
		r0 = returnFunc(ctx, guildID, actor, form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.FormOutcome)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, reservation.Actor, reservation.Form) error); ok {
		r1 = returnFunc(ctx, guildID, actor, form)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationFormService_BookForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookForm'
type MockReservationFormService_BookForm_Call struct {
	*mock.Call
}

// BookForm is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - actor reservation.Actor
//   - form reservation.Form
func (_e *MockReservationFormService_Expecter) BookForm(ctx any, guildID any, actor any, form any) *MockReservationFormService_BookForm_Call {
	return &MockReservationFormService_BookForm_Call{Call: _e.mock.On("BookForm", ctx, guildID, actor, form)}
}

func (_c *MockReservationFormService_BookForm_Call) Run(run func(ctx context.Context, guildID string, actor reservation.Actor, form reservation.Form)) *MockReservationFormService_BookForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 reservation.Actor
		if args[2] != nil {
			arg2 = args[2].(reservation.Actor)
		}
		var arg3 reservation.Form
		if args[3] != nil {
			arg3 = args[3].(reservation.Form)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReservationFormService_BookForm_Call) Return(formOutcome *reservation.FormOutcome, err error) *MockReservationFormService_BookForm_Call {
	_c.Call.Return(formOutcome, err)
	return _c
}

func (_c *MockReservationFormService_BookForm_Call) RunAndReturn(run func(ctx context.Context, guildID string, actor reservation.Actor, form reservation.Form) (*reservation.FormOutcome, error)) *MockReservationFormService_BookForm_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function for the type MockReservationFormService
func (_mock *MockReservationFormService) Cancel(ctx context.Context, guildID string, actor reservation.Actor, id int64) (*reservation.ReservationWithSpot, error) {
	ret := _mock.Called(ctx, guildID, actor, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 *reservation.ReservationWithSpot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64) (*reservation.ReservationWithSpot, error)); ok {
		return returnFunc(ctx, guildID, actor, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64) *reservation.ReservationWithSpot); ok {
		r0 = returnFunc(ctx, guildID, actor, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.ReservationWithSpot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, reservation.Actor, int64) error); ok {
		r1 = returnFunc(ctx, guildID, actor, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationFormService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockReservationFormService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - actor reservation.Actor
//   - id int64
func (_e *MockReservationFormService_Expecter) Cancel(ctx any, guildID any, actor any, id any) *MockReservationFormService_Cancel_Call {
	return &MockReservationFormService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, guildID, actor, id)}
}

func (_c *MockReservationFormService_Cancel_Call) Run(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64)) *MockReservationFormService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 reservation.Actor
		if args[2] != nil {
			arg2 = args[2].(reservation.Actor)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReservationFormService_Cancel_Call) Return(reservationWithSpot *reservation.ReservationWithSpot, err error) *MockReservationFormService_Cancel_Call {
	_c.Call.Return(reservationWithSpot, err)
	return _c
}

func (_c *MockReservationFormService_Cancel_Call) RunAndReturn(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64) (*reservation.ReservationWithSpot, error)) *MockReservationFormService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Cancellable provides a mock function for the type MockReservationFormService
func (_mock *MockReservationFormService) Cancellable(ctx context.Context, guildID string, actor reservation.Actor, id int64) (*reservation.ReservationWithSpot, error) {
	ret := _mock.Called(ctx, guildID, actor, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancellable")
	}

	var r0 *reservation.ReservationWithSpot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64) (*reservation.ReservationWithSpot, error)); ok {
		return returnFunc(ctx, guildID, actor, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64) *reservation.ReservationWithSpot); ok {
		r0 = returnFunc(ctx, guildID, actor, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.ReservationWithSpot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, reservation.Actor, int64) error); ok {
		r1 = returnFunc(ctx, guildID, actor, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationFormService_Cancellable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancellable'
type MockReservationFormService_Cancellable_Call struct {
	*mock.Call
}

// Cancellable is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - actor reservation.Actor
//   - id int64
func (_e *MockReservationFormService_Expecter) Cancellable(ctx any, guildID any, actor any, id any) *MockReservationFormService_Cancellable_Call {
	return &MockReservationFormService_Cancellable_Call{Call: _e.mock.On("Cancellable", ctx, guildID, actor, id)}
}

func (_c *MockReservationFormService_Cancellable_Call) Run(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64)) *MockReservationFormService_Cancellable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 reservation.Actor
		if args[2] != nil {
			arg2 = args[2].(reservation.Actor)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReservationFormService_Cancellable_Call) Return(reservationWithSpot *reservation.ReservationWithSpot, err error) *MockReservationFormService_Cancellable_Call {
	_c.Call.Return(reservationWithSpot, err)
	return _c
}

func (_c *MockReservationFormService_Cancellable_Call) RunAndReturn(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64) (*reservation.ReservationWithSpot, error)) *MockReservationFormService_Cancellable_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function for the type MockReservationFormService
func (_mock *MockReservationFormService) Edit(ctx context.Context, guildID string, actor reservation.Actor, id int64, draft reservation.Draft) (*reservation.FormOutcome, error) {
	ret := _mock.Called(ctx, guildID, actor, id, draft)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 *reservation.FormOutcome
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64, reservation.Draft) (*reservation.FormOutcome, error)); ok {
		return returnFunc(ctx, guildID, actor, id, draft)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64, reservation.Draft) *reservation.FormOutcome); ok {
		r0 = returnFunc(ctx, guildID, actor, id, draft)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.FormOutcome)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, reservation.Actor, int64, reservation.Draft) error); ok {
		r1 = returnFunc(ctx, guildID, actor, id, draft)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationFormService_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type MockReservationFormService_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - actor reservation.Actor
//   - id int64
//   - draft reservation.Draft
func (_e *MockReservationFormService_Expecter) Edit(ctx any, guildID any, actor any, id any, draft any) *MockReservationFormService_Edit_Call {
	return &MockReservationFormService_Edit_Call{Call: _e.mock.On("Edit", ctx, guildID, actor, id, draft)}
}

func (_c *MockReservationFormService_Edit_Call) Run(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64, draft reservation.Draft)) *MockReservationFormService_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 reservation.Actor
		if args[2] != nil {
			arg2 = args[2].(reservation.Actor)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 reservation.Draft
		if args[4] != nil {
			arg4 = args[4].(reservation.Draft)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReservationFormService_Edit_Call) Return(formOutcome *reservation.FormOutcome, err error) *MockReservationFormService_Edit_Call {
	_c.Call.Return(formOutcome, err)
	return _c
}

func (_c *MockReservationFormService_Edit_Call) RunAndReturn(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64, draft reservation.Draft) (*reservation.FormOutcome, error)) *MockReservationFormService_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// EditForm provides a mock function for the type MockReservationFormService
func (_mock *MockReservationFormService) EditForm(ctx context.Context, guildID string, actor reservation.Actor, id int64, form reservation.Form) (*reservation.FormOutcome, error) {
	ret := _mock.Called(ctx, guildID, actor, id, form)

	if len(ret) == 0 {
		panic("no return value specified for EditForm")
	}

	var r0 *reservation.FormOutcome
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64, reservation.Form) (*reservation.FormOutcome, error)); ok {
		return returnFunc(ctx, guildID, actor, id, form)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64, reservation.Form) *reservation.FormOutcome); ok {
		r0 = returnFunc(ctx, guildID, actor, id, form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.FormOutcome)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, reservation.Actor, int64, reservation.Form) error); ok {
		r1 = returnFunc(ctx, guildID, actor, id, form)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationFormService_EditForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditForm'
type MockReservationFormService_EditForm_Call struct {
	*mock.Call
}

// EditForm is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - actor reservation.Actor
//   - id int64
//   - form reservation.Form
func (_e *MockReservationFormService_Expecter) EditForm(ctx any, guildID any, actor any, id any, form any) *MockReservationFormService_EditForm_Call {
	return &MockReservationFormService_EditForm_Call{Call: _e.mock.On("EditForm", ctx, guildID, actor, id, form)}
}

func (_c *MockReservationFormService_EditForm_Call) Run(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64, form reservation.Form)) *MockReservationFormService_EditForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 reservation.Actor
		if args[2] != nil {
			arg2 = args[2].(reservation.Actor)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 reservation.Form
		if args[4] != nil {
			arg4 = args[4].(reservation.Form)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReservationFormService_EditForm_Call) Return(formOutcome *reservation.FormOutcome, err error) *MockReservationFormService_EditForm_Call {
	_c.Call.Return(formOutcome, err)
	return _c
}

func (_c *MockReservationFormService_EditForm_Call) RunAndReturn(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64, form reservation.Form) (*reservation.FormOutcome, error)) *MockReservationFormService_EditForm_Call {
	_c.Call.Return(run)
	return _c
}

// Editable provides a mock function for the type MockReservationFormService
func (_mock *MockReservationFormService) Editable(ctx context.Context, guildID string, actor reservation.Actor, id int64) (*reservation.ReservationWithSpot, error) {
	ret := _mock.Called(ctx, guildID, actor, id)

	if len(ret) == 0 {
		panic("no return value specified for Editable")
	}

	var r0 *reservation.ReservationWithSpot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64) (*reservation.ReservationWithSpot, error)); ok {
		return returnFunc(ctx, guildID, actor, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int64) *reservation.ReservationWithSpot); ok {
		r0 = returnFunc(ctx, guildID, actor, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.ReservationWithSpot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, reservation.Actor, int64) error); ok {
		r1 = returnFunc(ctx, guildID, actor, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationFormService_Editable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Editable'
type MockReservationFormService_Editable_Call struct {
	*mock.Call
}

// Editable is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - actor reservation.Actor
//   - id int64
func (_e *MockReservationFormService_Expecter) Editable(ctx any, guildID any, actor any, id any) *MockReservationFormService_Editable_Call {
	return &MockReservationFormService_Editable_Call{Call: _e.mock.On("Editable", ctx, guildID, actor, id)}
}

func (_c *MockReservationFormService_Editable_Call) Run(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64)) *MockReservationFormService_Editable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 reservation.Actor
		if args[2] != nil {
			arg2 = args[2].(reservation.Actor)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReservationFormService_Editable_Call) Return(reservationWithSpot *reservation.ReservationWithSpot, err error) *MockReservationFormService_Editable_Call {
	_c.Call.Return(reservationWithSpot, err)
	return _c
}

func (_c *MockReservationFormService_Editable_Call) RunAndReturn(run func(ctx context.Context, guildID string, actor reservation.Actor, id int64) (*reservation.ReservationWithSpot, error)) *MockReservationFormService_Editable_Call {
	_c.Call.Return(run)
	return _c
}

// Mine provides a mock function for the type MockReservationFormService
func (_mock *MockReservationFormService) Mine(ctx context.Context, guildID string, actor reservation.Actor, limit int) (*reservation.Page, error) {
	ret := _mock.Called(ctx, guildID, actor, limit)

	if len(ret) == 0 {
		panic("no return value specified for Mine")
	}

	var r0 *reservation.Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int) (*reservation.Page, error)); ok {
		return returnFunc(ctx, guildID, actor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, reservation.Actor, int) *reservation.Page); ok {
		r0 = returnFunc(ctx, guildID, actor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservation.Page)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, reservation.Actor, int) error); ok {
		r1 = returnFunc(ctx, guildID, actor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservationFormService_Mine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mine'
type MockReservationFormService_Mine_Call struct {
	*mock.Call
}

// Mine is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - actor reservation.Actor
//   - limit int
func (_e *MockReservationFormService_Expecter) Mine(ctx any, guildID any, actor any, limit any) *MockReservationFormService_Mine_Call {
	return &MockReservationFormService_Mine_Call{Call: _e.mock.On("Mine", ctx, guildID, actor, limit)}
}

func (_c *MockReservationFormService_Mine_Call) Run(run func(ctx context.Context, guildID string, actor reservation.Actor, limit int)) *MockReservationFormService_Mine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 reservation.Actor
		if args[2] != nil {
			arg2 = args[2].(reservation.Actor)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReservationFormService_Mine_Call) Return(page *reservation.Page, err error) *MockReservationFormService_Mine_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockReservationFormService_Mine_Call) RunAndReturn(run func(ctx context.Context, guildID string, actor reservation.Actor, limit int) (*reservation.Page, error)) *MockReservationFormService_Mine_Call {
	_c.Call.Return(run)
	return _c
}
