// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/spot"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSpotRepository creates a new instance of MockSpotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpotRepository {
	mock := &MockSpotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpotRepository is an autogenerated mock type for the SpotRepository type
type MockSpotRepository struct {
	mock.Mock
}

type MockSpotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpotRepository) EXPECT() *MockSpotRepository_Expecter {
	return &MockSpotRepository_Expecter{mock: &_m.Mock}
}

// SelectAllSpots provides a mock function for the type MockSpotRepository
func (_mock *MockSpotRepository) SelectAllSpots(ctx context.Context) ([]*spot.Spot, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SelectAllSpots")
	}

	var r0 []*spot.Spot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*spot.Spot, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*spot.Spot); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*spot.Spot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpotRepository_SelectAllSpots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectAllSpots'
type MockSpotRepository_SelectAllSpots_Call struct {
	*mock.Call
}

// SelectAllSpots is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSpotRepository_Expecter) SelectAllSpots(ctx interface{}) *MockSpotRepository_SelectAllSpots_Call {
	return &MockSpotRepository_SelectAllSpots_Call{Call: _e.mock.On("SelectAllSpots", ctx)}
}

func (_c *MockSpotRepository_SelectAllSpots_Call) Run(run func(ctx context.Context)) *MockSpotRepository_SelectAllSpots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSpotRepository_SelectAllSpots_Call) Return(spots []*spot.Spot, err error) *MockSpotRepository_SelectAllSpots_Call {
	_c.Call.Return(spots, err)
	return _c
}

func (_c *MockSpotRepository_SelectAllSpots_Call) RunAndReturn(run func(ctx context.Context) ([]*spot.Spot, error)) *MockSpotRepository_SelectAllSpots_Call {
	_c.Call.Return(run)
	return _c
}
