// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"spot-assistant/internal/core/dto/stats"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStatsRow creates a new instance of MockStatsRow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsRow {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStatsRow{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStatsRow is an autogenerated mock type for the StatsRow type
type MockStatsRow struct {
	mock.Mock
}

type MockStatsRow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsRow) EXPECT() *MockStatsRow_Expecter {
	return &MockStatsRow_Expecter{mock: &_m.Mock}
}

// Label provides a mock function for the type MockStatsRow
func (_mock *MockStatsRow) Label() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Label")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStatsRow_Label_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Label'
type MockStatsRow_Label_Call struct {
	*mock.Call
}

// Label is a helper method to define mock.On call
func (_e *MockStatsRow_Expecter) Label() *MockStatsRow_Label_Call {
	return &MockStatsRow_Label_Call{Call: _e.mock.On("Label")}
}

func (_c *MockStatsRow_Label_Call) Run(run func()) *MockStatsRow_Label_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatsRow_Label_Call) Return(s string) *MockStatsRow_Label_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStatsRow_Label_Call) RunAndReturn(run func() string) *MockStatsRow_Label_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockStatsRow
func (_mock *MockStatsRow) Stats() stats.Totals {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 stats.Totals
	if returnFunc, ok := ret.Get(0).(func() stats.Totals); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(stats.Totals)
	}
	return r0
}

// MockStatsRow_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockStatsRow_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockStatsRow_Expecter) Stats() *MockStatsRow_Stats_Call {
	return &MockStatsRow_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockStatsRow_Stats_Call) Run(run func()) *MockStatsRow_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatsRow_Stats_Call) Return(totals stats.Totals) *MockStatsRow_Stats_Call {
	_c.Call.Return(totals)
	return _c
}

func (_c *MockStatsRow_Stats_Call) RunAndReturn(run func() stats.Totals) *MockStatsRow_Stats_Call {
	_c.Call.Return(run)
	return _c
}
