// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"spot-assistant/internal/core/dto/book"
	"spot-assistant/internal/core/dto/member"
	"spot-assistant/internal/core/dto/reservation"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTextFormatter creates a new instance of MockTextFormatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTextFormatter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTextFormatter {
	mock := &MockTextFormatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTextFormatter is an autogenerated mock type for the TextFormatter type
type MockTextFormatter struct {
	mock.Mock
}

type MockTextFormatter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTextFormatter) EXPECT() *MockTextFormatter_Expecter {
	return &MockTextFormatter_Expecter{mock: &_m.Mock}
}

// FormatBookError provides a mock function for the type MockTextFormatter
func (_mock *MockTextFormatter) FormatBookError(response book.BookResponse, err error) string {
	ret := _mock.Called(response, err)

	if len(ret) == 0 {
		panic("no return value specified for FormatBookError")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(book.BookResponse, error) string); ok {
		r0 = returnFunc(response, err)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTextFormatter_FormatBookError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatBookError'
type MockTextFormatter_FormatBookError_Call struct {
	*mock.Call
}

// FormatBookError is a helper method to define mock.On call
//   - response book.BookResponse
//   - err error
func (_e *MockTextFormatter_Expecter) FormatBookError(response interface{}, err interface{}) *MockTextFormatter_FormatBookError_Call {
	return &MockTextFormatter_FormatBookError_Call{Call: _e.mock.On("FormatBookError", response, err)}
}

func (_c *MockTextFormatter_FormatBookError_Call) Run(run func(response book.BookResponse, err error)) *MockTextFormatter_FormatBookError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 book.BookResponse
		if args[0] != nil {
			arg0 = args[0].(book.BookResponse)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTextFormatter_FormatBookError_Call) Return(s string) *MockTextFormatter_FormatBookError_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTextFormatter_FormatBookError_Call) RunAndReturn(run func(response book.BookResponse, err error) string) *MockTextFormatter_FormatBookError_Call {
	_c.Call.Return(run)
	return _c
}

// FormatBookResponse provides a mock function for the type MockTextFormatter
func (_mock *MockTextFormatter) FormatBookResponse(response book.BookResponse) string {
	ret := _mock.Called(response)

	if len(ret) == 0 {
		panic("no return value specified for FormatBookResponse")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(book.BookResponse) string); ok {
		r0 = returnFunc(response)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTextFormatter_FormatBookResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatBookResponse'
type MockTextFormatter_FormatBookResponse_Call struct {
	*mock.Call
}

// FormatBookResponse is a helper method to define mock.On call
//   - response book.BookResponse
func (_e *MockTextFormatter_Expecter) FormatBookResponse(response interface{}) *MockTextFormatter_FormatBookResponse_Call {
	return &MockTextFormatter_FormatBookResponse_Call{Call: _e.mock.On("FormatBookResponse", response)}
}

func (_c *MockTextFormatter_FormatBookResponse_Call) Run(run func(response book.BookResponse)) *MockTextFormatter_FormatBookResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 book.BookResponse
		if args[0] != nil {
			arg0 = args[0].(book.BookResponse)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTextFormatter_FormatBookResponse_Call) Return(s string) *MockTextFormatter_FormatBookResponse_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTextFormatter_FormatBookResponse_Call) RunAndReturn(run func(response book.BookResponse) string) *MockTextFormatter_FormatBookResponse_Call {
	_c.Call.Return(run)
	return _c
}

// FormatGenericError provides a mock function for the type MockTextFormatter
func (_mock *MockTextFormatter) FormatGenericError(err error) string {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for FormatGenericError")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(error) string); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTextFormatter_FormatGenericError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatGenericError'
type MockTextFormatter_FormatGenericError_Call struct {
	*mock.Call
}

// FormatGenericError is a helper method to define mock.On call
//   - err error
func (_e *MockTextFormatter_Expecter) FormatGenericError(err interface{}) *MockTextFormatter_FormatGenericError_Call {
	return &MockTextFormatter_FormatGenericError_Call{Call: _e.mock.On("FormatGenericError", err)}
}

func (_c *MockTextFormatter_FormatGenericError_Call) Run(run func(err error)) *MockTextFormatter_FormatGenericError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTextFormatter_FormatGenericError_Call) Return(s string) *MockTextFormatter_FormatGenericError_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTextFormatter_FormatGenericError_Call) RunAndReturn(run func(err error) string) *MockTextFormatter_FormatGenericError_Call {
	_c.Call.Return(run)
	return _c
}

// FormatOverbookedMemberNotification provides a mock function for the type MockTextFormatter
func (_mock *MockTextFormatter) FormatOverbookedMemberNotification(member1 *member.Member, request book.BookRequest, res *reservation.ClippedOrRemovedReservation) string {
	ret := _mock.Called(member1, request, res)

	if len(ret) == 0 {
		panic("no return value specified for FormatOverbookedMemberNotification")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*member.Member, book.BookRequest, *reservation.ClippedOrRemovedReservation) string); ok {
		r0 = returnFunc(member1, request, res)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTextFormatter_FormatOverbookedMemberNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatOverbookedMemberNotification'
type MockTextFormatter_FormatOverbookedMemberNotification_Call struct {
	*mock.Call
}

// FormatOverbookedMemberNotification is a helper method to define mock.On call
//   - member1 *member.Member
//   - request book.BookRequest
//   - res *reservation.ClippedOrRemovedReservation
func (_e *MockTextFormatter_Expecter) FormatOverbookedMemberNotification(member1 interface{}, request interface{}, res interface{}) *MockTextFormatter_FormatOverbookedMemberNotification_Call {
	return &MockTextFormatter_FormatOverbookedMemberNotification_Call{Call: _e.mock.On("FormatOverbookedMemberNotification", member1, request, res)}
}

func (_c *MockTextFormatter_FormatOverbookedMemberNotification_Call) Run(run func(member1 *member.Member, request book.BookRequest, res *reservation.ClippedOrRemovedReservation)) *MockTextFormatter_FormatOverbookedMemberNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *member.Member
		if args[0] != nil {
			arg0 = args[0].(*member.Member)
		}
		var arg1 book.BookRequest
		if args[1] != nil {
			arg1 = args[1].(book.BookRequest)
		}
		var arg2 *reservation.ClippedOrRemovedReservation
		if args[2] != nil {
			arg2 = args[2].(*reservation.ClippedOrRemovedReservation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTextFormatter_FormatOverbookedMemberNotification_Call) Return(s string) *MockTextFormatter_FormatOverbookedMemberNotification_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTextFormatter_FormatOverbookedMemberNotification_Call) RunAndReturn(run func(member1 *member.Member, request book.BookRequest, res *reservation.ClippedOrRemovedReservation) string) *MockTextFormatter_FormatOverbookedMemberNotification_Call {
	_c.Call.Return(run)
	return _c
}

// FormatUpcomingReservationNotificationMessage provides a mock function for the type MockTextFormatter
func (_mock *MockTextFormatter) FormatUpcomingReservationNotificationMessage(spotName string, startAt time.Time, now time.Time) string {
	ret := _mock.Called(spotName, startAt, now)

	if len(ret) == 0 {
		panic("no return value specified for FormatUpcomingReservationNotificationMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, time.Time, time.Time) string); ok {
		r0 = returnFunc(spotName, startAt, now)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatUpcomingReservationNotificationMessage'
type MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call struct {
	*mock.Call
}

// FormatUpcomingReservationNotificationMessage is a helper method to define mock.On call
//   - spotName string
//   - startAt time.Time
//   - now time.Time
func (_e *MockTextFormatter_Expecter) FormatUpcomingReservationNotificationMessage(spotName interface{}, startAt interface{}, now interface{}) *MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call {
	return &MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call{Call: _e.mock.On("FormatUpcomingReservationNotificationMessage", spotName, startAt, now)}
}

func (_c *MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call) Run(run func(spotName string, startAt time.Time, now time.Time)) *MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call) Return(s string) *MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call) RunAndReturn(run func(spotName string, startAt time.Time, now time.Time) string) *MockTextFormatter_FormatUpcomingReservationNotificationMessage_Call {
	_c.Call.Return(run)
	return _c
}
