// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spot-assistant/internal/core/dto/webuser"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWebUserRepository creates a new instance of MockWebUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebUserRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockWebUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockWebUserRepository is an autogenerated mock type for the WebUserRepository type
type MockWebUserRepository struct {
	mock.Mock
}

type MockWebUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebUserRepository) EXPECT() *MockWebUserRepository_Expecter {
	return &MockWebUserRepository_Expecter{mock: &_m.Mock}
}

// AccessToken provides a mock function for the type MockWebUserRepository
func (_mock *MockWebUserRepository) AccessToken(ctx context.Context, discordUserID string) (*webuser.Token, error) {
	ret := _mock.Called(ctx, discordUserID)

	if len(ret) == 0 {
		panic("no return value specified for AccessToken")
	}

	var r0 *webuser.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*webuser.Token, error)); ok {
		return returnFunc(ctx, discordUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *webuser.Token); ok {
		r0 = returnFunc(ctx, discordUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webuser.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, discordUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebUserRepository_AccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessToken'
type MockWebUserRepository_AccessToken_Call struct {
	*mock.Call
}

// AccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - discordUserID string
func (_e *MockWebUserRepository_Expecter) AccessToken(ctx any, discordUserID any) *MockWebUserRepository_AccessToken_Call {
	return &MockWebUserRepository_AccessToken_Call{Call: _e.mock.On("AccessToken", ctx, discordUserID)}
}

func (_c *MockWebUserRepository_AccessToken_Call) Run(run func(ctx context.Context, discordUserID string)) *MockWebUserRepository_AccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebUserRepository_AccessToken_Call) Return(token *webuser.Token, err error) *MockWebUserRepository_AccessToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockWebUserRepository_AccessToken_Call) RunAndReturn(run func(ctx context.Context, discordUserID string) (*webuser.Token, error)) *MockWebUserRepository_AccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWebUserRepository
func (_mock *MockWebUserRepository) Get(ctx context.Context, discordUserID string) (*webuser.User, error) {
	ret := _mock.Called(ctx, discordUserID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *webuser.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*webuser.User, error)); ok {
		return returnFunc(ctx, discordUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *webuser.User); ok {
		r0 = returnFunc(ctx, discordUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webuser.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, discordUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebUserRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWebUserRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - discordUserID string
func (_e *MockWebUserRepository_Expecter) Get(ctx any, discordUserID any) *MockWebUserRepository_Get_Call {
	return &MockWebUserRepository_Get_Call{Call: _e.mock.On("Get", ctx, discordUserID)}
}

func (_c *MockWebUserRepository_Get_Call) Run(run func(ctx context.Context, discordUserID string)) *MockWebUserRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebUserRepository_Get_Call) Return(user *webuser.User, err error) *MockWebUserRepository_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockWebUserRepository_Get_Call) RunAndReturn(run func(ctx context.Context, discordUserID string) (*webuser.User, error)) *MockWebUserRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function for the type MockWebUserRepository
func (_mock *MockWebUserRepository) SaveToken(ctx context.Context, discordUserID string, token webuser.Token) error {
	ret := _mock.Called(ctx, discordUserID, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, webuser.Token) error); ok {
		r0 = returnFunc(ctx, discordUserID, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebUserRepository_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type MockWebUserRepository_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - discordUserID string
//   - token webuser.Token
func (_e *MockWebUserRepository_Expecter) SaveToken(ctx any, discordUserID any, token any) *MockWebUserRepository_SaveToken_Call {
	return &MockWebUserRepository_SaveToken_Call{Call: _e.mock.On("SaveToken", ctx, discordUserID, token)}
}

func (_c *MockWebUserRepository_SaveToken_Call) Run(run func(ctx context.Context, discordUserID string, token webuser.Token)) *MockWebUserRepository_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 webuser.Token
		if args[2] != nil {
			arg2 = args[2].(webuser.Token)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebUserRepository_SaveToken_Call) Return(err error) *MockWebUserRepository_SaveToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebUserRepository_SaveToken_Call) RunAndReturn(run func(ctx context.Context, discordUserID string, token webuser.Token) error) *MockWebUserRepository_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockWebUserRepository
func (_mock *MockWebUserRepository) Upsert(ctx context.Context, user webuser.User) (*webuser.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *webuser.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, webuser.User) (*webuser.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, webuser.User) *webuser.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webuser.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, webuser.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebUserRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockWebUserRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - user webuser.User
func (_e *MockWebUserRepository_Expecter) Upsert(ctx any, user any) *MockWebUserRepository_Upsert_Call {
	return &MockWebUserRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, user)}
}

func (_c *MockWebUserRepository_Upsert_Call) Run(run func(ctx context.Context, user webuser.User)) *MockWebUserRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 webuser.User
		if args[1] != nil {
			arg1 = args[1].(webuser.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebUserRepository_Upsert_Call) Return(user1 *webuser.User, err error) *MockWebUserRepository_Upsert_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockWebUserRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, user webuser.User) (*webuser.User, error)) *MockWebUserRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
