// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorldAPI creates a new instance of MockWorldAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorldAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorldAPI {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockWorldAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockWorldAPI is an autogenerated mock type for the WorldAPI type
type MockWorldAPI struct {
	mock.Mock
}

type MockWorldAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorldAPI) EXPECT() *MockWorldAPI_Expecter {
	return &MockWorldAPI_Expecter{mock: &_m.Mock}
}

// GetBaseURL provides a mock function for the type MockWorldAPI
func (_mock *MockWorldAPI) GetBaseURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBaseURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWorldAPI_GetBaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBaseURL'
type MockWorldAPI_GetBaseURL_Call struct {
	*mock.Call
}

// GetBaseURL is a helper method to define mock.On call
func (_e *MockWorldAPI_Expecter) GetBaseURL() *MockWorldAPI_GetBaseURL_Call {
	return &MockWorldAPI_GetBaseURL_Call{Call: _e.mock.On("GetBaseURL")}
}

func (_c *MockWorldAPI_GetBaseURL_Call) Run(run func()) *MockWorldAPI_GetBaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWorldAPI_GetBaseURL_Call) Return(s string) *MockWorldAPI_GetBaseURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWorldAPI_GetBaseURL_Call) RunAndReturn(run func() string) *MockWorldAPI_GetBaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetOnlinePlayerNames provides a mock function for the type MockWorldAPI
func (_mock *MockWorldAPI) GetOnlinePlayerNames(worldName string) ([]string, error) {
	ret := _mock.Called(worldName)

	if len(ret) == 0 {
		panic("no return value specified for GetOnlinePlayerNames")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(worldName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(worldName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(worldName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorldAPI_GetOnlinePlayerNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnlinePlayerNames'
type MockWorldAPI_GetOnlinePlayerNames_Call struct {
	*mock.Call
}

// GetOnlinePlayerNames is a helper method to define mock.On call
//   - worldName string
func (_e *MockWorldAPI_Expecter) GetOnlinePlayerNames(worldName any) *MockWorldAPI_GetOnlinePlayerNames_Call {
	return &MockWorldAPI_GetOnlinePlayerNames_Call{Call: _e.mock.On("GetOnlinePlayerNames", worldName)}
}

func (_c *MockWorldAPI_GetOnlinePlayerNames_Call) Run(run func(worldName string)) *MockWorldAPI_GetOnlinePlayerNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorldAPI_GetOnlinePlayerNames_Call) Return(strings []string, err error) *MockWorldAPI_GetOnlinePlayerNames_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockWorldAPI_GetOnlinePlayerNames_Call) RunAndReturn(run func(worldName string) ([]string, error)) *MockWorldAPI_GetOnlinePlayerNames_Call {
	_c.Call.Return(run)
	return _c
}
