version: "2"
sql:
  - engine: "postgresql"
    queries: ["query/guilds.sql", "query/channels.sql", "query/roles.sql"]
    schema: "../../db/postgresql/migrations"
    gen:
      go:
        package: "sqlc"
        sql_package: "pgx/v5"
        out: "sqlc"
