name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    # services:
    #   # Label used to access the service container
    #   postgres:
    #     # Docker Hub image
    #     image: postgres:12
    #     # Provide the password for postgres
    #     env:
    #       POSTGRES_PASSWORD: test
    #       POSTGRES_DB: test
    #     # Set health checks to wait until postgres has started
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5431:5432

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.21"

      - uses: sqlc-dev/setup-sqlc@v3
        with:
          sqlc-version: "1.21.0"

      - name: Install dependencies
        run: make install-dependencies

      - name: Run tests
        run: make test
